<div class="main-container">
	<div class="container main wrapper clearfix">
		<div class="row-fluid">
			<div class="span12 recuperacion">
	            <h1>Recuperación de Contraseña</h1>
	            <small>
	                Si ha olvidado su contraseña, introduzca su dirección de correo electrónico debajo y le enviaremos las instrucciones para cambiar su contraseña.
	            </small>
                    <?php
                            $form = $this->form;
                            $form->setAttributes(array(
                                'action' => $this->url.'/cambio', 
                                'method' => 'post',
//                                'class'=>'span12 form-crear-grupo',
//                                'id'=>'crear-group'
                            ));

                            $form->prepare();
                            echo $this->form()->openTag($form);
                    ?>
	            <!--<form action="" id="recuperacion">-->
	                <p>
	                <label for="">Correo Electrónico</label>
                         <?php echo $this->formRow($form->get('va_email'));?>
	                <!--<input type="email" id="va_email" name="va_email" placeholder="yourmail@email.com">-->
	                </p> 
                          <?php echo $this->formSubmit($form->get('submit'));?>
	                <!--<input type="submit" value="Enviar">-->                       
	            </form>
	        </div>
                    <div class="alert alert-success"><?php echo $this->mensaje[0];?></div>
		</div>
	</div>
</div> <!-- #main-container -->