<div class="main-container">
	<div class="container main wrapper clearfix">
		<?php if($this->mensaje[0]){?>
		<div class="row-fluid">
			<div class="alert alert-success" style="margin-bottom:0;margin-top:20px;"><?php echo $this->mensaje[0];?></div>
		</div>
		<?php }?>
		<div class="row-fluid">
			<div class="span12 recuperacion group-sidebar">
	            <h1>Recuperación de Contraseña</h1>
	            <small>
	                Si ha olvidado su contraseña, introduzca su dirección de correo electrónico debajo y le enviaremos las instrucciones para cambiar su contraseña.
	            </small>
                    <?php
                            $form = $this->form;
                            $form->setAttributes(array(
                                'action' => $this->url.'/cambio', 
                                'method' => 'post',
                                'id' => 'recuperacion'
                            ));

                            $form->prepare();
                            echo $this->form()->openTag($form);
                    ?>
	                <p>
	                <label for="">Correo Electrónico</label>
                         <?php echo $this->formRow($form->get('va_email'));?>
	                </p> 
                          <?php echo $this->formSubmit($form->get('submit'));?>                 
	            </form>
	        </div>      
		</div>
	</div>
</div> <!-- #main-container -->