<div class="main-container">
	<div class="container">
		<div class="row-fluid">
			<div class="span12">
				<form class="form-recuperar-contra">
					<h3>Ingrese su nueva contraseña</h3>
					<div class="row-fluid">
						<label for="pass">Contraseña:</label>
						<input type="password" class="span10" name="nm-password" placeholder="Ingrese su contraseña">
					</div>
					<div class="row-fluid">
						<label for="pass">Repita contraseña:</label>
						<input type="password" class="span10" name="re-password" placeholder="Vuelva a ingresar su contraseña">
					</div>
		            <div class="row-fluid">
		            	<input type="submit" class="btn" id="btn-recuperar" value="Guardar"/>
		            </div>
	          	</form>
			</div>
		</div>
	</div>
</div>