<script type="text/javascript" src="<?php echo $this->host('ruta')?>/js/jquery.validate.min.js"></script>
<div class="main-container">
	<div class="container">
        <?php if($this->mensaje[0]){?>
        <div class="row-fluid">
        	<div class="alert alert-success" style="margin-bottom:0;margin-top:20px;"><?php echo $this->mensaje[0];?></div>
        </div>
		<?php }?>
		<div class="row-fluid">
			<div class="span12 recuperacion group-sidebar">
			<?php 
			$form = $this->form;
			$form->setAttributes(array(
			    'action' => $this->url.'/cambio-contrasena?contrasena='.$this->password,
			    'method' => 'post',
			    'class'=>'span12 form-crear-usuario',
			    'id'=>'registro'
			));
			$form->prepare();
			echo $this->form()->openTag($form);
			
			?>
					<h3>Ingrese su nueva contraseña</h3>
					<div class="row-fluid">
						<label for="pass">Contraseña:</label>
						<?php echo $this->formrow($form->get('va_contrasena'))?>
					</div>
					<div class="row-fluid">
						<label for="pass">Repita contraseña:</label>
						<?php echo $this->formrow($form->get('verificar_contrasena'))?>
					</div>
		            <div class="row-fluid">
		             <?php echo $this->formSubmit($form->get('submit'));?>
		            </div>
		            <?php echo $this->form()->closeTag();?>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$("#registro").validate({
            rules: {
                va_contrasena:{
	                required : true,
	                minlength:8             
	            },
	            verificar_contrasena:{
	                required : true,
	                equalTo: "#va_contrasena",
	                minlength:8               
	            }
            },
            messages: {
              	va_contrasena: {
	                required : "Ingrese la clave",
	                minlength:"Ingresa un password de 8 caracteres a mas"
	            },
	            verificar_contrasena: {
	                required : "Repita la clave",            
	                minlength:"Ingresa un password de 8 caracteres a mas",
	                equalTo : "Ingrese el mismo valor de Clave"
	            }
            }
        });
	});
</script>