<div class="main-container">
	<div class="container">
		<div class="row-fluid">
			<div class="span12 recuperacion group-sidebar">
			<?php 
			$form = $this->form;
			$form->setAttributes(array(
			    'action' => $this->url.'/cambio-contrasena?contrasena='.$this->password,
			    'method' => 'post',
			    'class'=>'span12 form-crear-usuario',
			    'id'=>'registro'
			));
			$form->prepare();
			echo $this->form()->openTag($form);
			
			?>
					<h3>Ingrese su nueva contraseña</h3>
					<div class="row-fluid">
						<label for="pass">Contraseña:</label>
						<?php echo $this->formrow($form->get('va_contrasena'))?>
					</div>
					<div class="row-fluid">
						<label for="pass">Repita contraseña:</label>
						<?php echo $this->formrow($form->get('verificar_contrasena'))?>
					</div>
		            <div class="row-fluid">
		             <?php echo $this->formSubmit($form->get('submit'));?>
		            </div>
		            <?php echo $this->form()->closeTag();?>
			</div>
		</div>
		<?php if($this->mensaje[0]){?>
		 <div class="alert alert-success"><?php echo $this->mensaje[0];?></div>
		 <?php }?>
	</div>
</div>