 <div class="main-container">
  <div class="container">
<?php if ($_GET['m']==1) { ?> <div class="row-fluid">
      <div class="alert alert-margin alert-message">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <?php  echo 'Tu cuenta está casi lista para usarse, solo tienes que activarla desde tu correo electrónico'; ?>
      </div>
    </div> <?php } ?>
    <?php if($this->mensaje){?>
    <div class="row-fluid">
      <div class="alert alert-margin alert-message">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <?php  echo $this->mensaje; ?>
      </div>
    </div>
   <?php } ?>
    <div class="row-fluid group-sidebar sep">
      <div class="span8 dep-ja">
        <?php
          $form = $this->form;
          $form->setAttributes(array(
            'action' => $this->url.'/registrarse',
            'method' => 'post',
            'class'=>'span12 form-crear-usuario',
            'id'=>'registro'
          ));

          $form->prepare();
          echo $this->form()->openTag($form);
        ?>
        <div class="span4 cambiofotouser">
          <h1>Registro de Usuario</h1>
          <p>Selecciona una Imagen para tu perfil</p>
          <div class="cambiofoto2">
            <div class="fileupload fileupload-new" data-provides="fileupload" >
              <div class="img-thu-user fileupload-new thumbnail">
                <img src="/img/foto-carnet.jpg" style="width:130px;height:130px;">
              </div>
              <div class="img-thu-user fileupload-preview fileupload-exists thumbnail" style="height: 130px;"></div>
              <div class="detalle-img">
                <span class="btn botonuser btn-file">
                  <span class="fileupload-new">Cargar una imagen</span>
                  <span class="fileupload-exists">Cambiar Imagen </span>
                   <?php echo $this->formRow($form->get('va_foto'));?>
                </span>
                <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remover</a>         
              </div>
            </div>      
          </div>
          
          </div>
          <div class="span8 registro">
          <?php echo $this->formHidden($form->get('in_id'));?>
          <span>(<strong> * </strong>) Por favor complete los campos requeridos</span>
            <p>
            <label for=""><strong> * </strong>Nombre Completo</label>
            <?php echo $this->formRow($form->get('va_nombre'));?>
            <!--<input type="text" id="va_nombre" name="va_nombre" placeholder="Ingrese su nombre completo">-->
            </p>
            
            <p>
            <label for=""><strong> * </strong>Correo Electrónico</label>
            <!--<input type="email" id="va_email" name="va_email" placeholder="Ingrese un correo electrónico">-->
            <?php echo $this->formRow($form->get('va_email'));?>
            </p>
            <p>
            <label for=""><strong> * </strong>Contraseña</label>
            <!--<input type="Text" id="va_contrasena" name="va_contrasena" placeholder="Ingrese un password">-->
            <!--<input type="password"  -->
            <?php echo $this->formRow($form->get('va_contrasena'));?>
            </p>
            <p>
            <label for=""><strong> * </strong>Confirmar contraseña</label>
            <?php echo $this->formRow($form->get('verificar_contrasena'));?>
            <!--<input type="password" id="va_contrasena2" name="va_contrasena2" placeholder="Confirme su password">-->
            </p>
            <!--<input type="submit" value="Registrarse">-->
            <?php echo $this->formSubmit($form->get('submit'));?>
        </div>
      
        <?php echo $this->form()->closeTag();?>

      </div>
      <div class="span4 cambiofotouser dev-marca-face">
          <h1>REGISTRARSE CON FACEBOOK</h1>
      <?php //if ($this->user): ?>
<!--      <a href="<?php// echo $this->logoutUrl; ?>">Logout</a>-->
     <?php if($this->user) { ?>
        <div>
        <a href="<?php echo $this->loginUrl; ?>"> <img src="/img/face.png"></a>
        </div>
      <?php } else { ?> 
        <div>
        <a href="<?php echo $this->loginUrl; ?>"> <img src="/img/face.png"></a>
        </div>
       <?php }  ?>      
      </div>
    </div>
  </div> <!-- #main -->
</div> <!-- #main-container -->
   
<script type="text/javascript">
  $(document).ready(function(){
    $(".alert-message").alert();
    window.setTimeout(function() { $(".alert-message").alert('close'); }, 15000);
  });
</script>