<div class="main-container">
  <div class="container">
      
    <div class="row-fluid">
        <?php
                    $form = $this->form;

                    $form->setAttributes(array(
                        'action' => $this->url.'/usuario/index/agregarusuario',
                        'method' => 'post',
                        'class'=>'span12 form-crear-usuario',
                        'id'=>'crear-user'
                    ));

                    $form->prepare();
                    echo $this->form()->openTag($form);
                    ?>
      <div class="span4 cambiofotouser">
        <h1>Registro de Usuario</h1>
        <p>Seleccione una Imagen para su perfil</p>
        <div class="cambiofoto2">
          <div class="fileupload fileupload-new" data-provides="fileupload" >
            <div class="img-thu-user fileupload-new thumbnail">
              <img src="/img/foto-carnet.jpg" style="width:130px;height:130px;">
            </div>
            <div class="img-thu-user fileupload-preview fileupload-exists thumbnail" style="height: 130px;"></div>
            <div class="detalle-img">
              <strong class="botonuser btn-file">
              <strong class="fileupload-new">Cargar una imagen</strong>
              <strong class="fileupload-exists">Cambiar Imagen </strong><input type="file" name='imagefile' />
               <?php echo $this->formRow($form->get('va_foto'));?>
              </strong>
              <a href="#" class="boton-rem-user fileupload-exists" data-dismiss="fileupload">Remover</a>         
            </div>
          </div>
        </div>      
      </div>
      <div class="span8 registro">
          <?php echo $this->formHidden($form->get('in_id'));?>
          <span>(<strong> * </strong>) Por favor complete los campos requeridos</span>
          <form action="" id="registro">
              <p>
              <label for=""><strong> * </strong>Nombre Completo</label>
              <?php echo $this->formRow($form->get('va_nombre'));?>
              <!--<input type="text" id="va_nombre" name="va_nombre" placeholder="Ingrese su nombre completo">-->
              </p>
              
              <p>
              <label for=""><strong> * </strong>Correo Electrónico</label>
<!--              <input type="email" id="va_email" name="va_email" placeholder="Ingrese un correo electrónico">-->
              <?php echo $this->formRow($form->get('va_email'));?>
              </p>
              <p>
              <label for=""><strong> * </strong>Password</label>
<!--              <input type="Text" id="va_contrasena" name="va_contraseña" placeholder="Ingrese un password">-->
              <input type="password" <?php echo $this->formRow($form->get('va_contraseña'));?> 
              </p>
<!--              <p>
              <label for=""><strong> * </strong>Confirmar Password</label>
              <input type="password" id="va_contrasena2" name="va_contrasena2" placeholder="Confirme su password">
              </p>-->
<!--              <input type="submit" value="Registrarse">-->
              <?php echo $this->formSubmit($form->get('submit'));?>
          </form>
      </div>
         <?php echo $this->form()->closeTag();?>
    </div>
     
  </div> <!-- #main -->
</div> <!-- #main-container -->
   
