<div class="main-container">
  <div class="container">
    <div class="row-fluid">
      <div class="span4 cambiofotouser">
        <h1>Registro de Usuario</h1>
        <p>Seleccione una Imagen para su perfil</p>
        <div class="cambiofoto2">
          <div class="fileupload fileupload-new" data-provides="fileupload" >
            <div class="img-thu-user fileupload-new thumbnail">
              <img src="/img/foto-carnet.jpg" style="width:130px;height:130px;">
            </div>
            <div class="img-thu-user fileupload-preview fileupload-exists thumbnail" style="height: 130px;"></div>
            <div class="detalle-img">
              <strong class="botonuser btn-file">
              <strong class="fileupload-new">Cargar una imagen</strong>
              <strong class="fileupload-exists">Cambiar Imagen </strong><input type="file" name='imagefile' /></strong>
              <a href="#" class="boton-rem-user fileupload-exists" data-dismiss="fileupload">Remover</a>         
            </div>
          </div>
        </div>      
      </div>
      <div class="span8 registro">
          <span>(<strong> * </strong>) Por favor complete los campos requeridos</span>
          <form action="" id="registro">
              <p>
              <label for=""><strong> * </strong>Nombre Completo</label>
              <input type="text" id="va_nombre" name="va_nombre" placeholder="Ingrese su nombre completo">
              </p>
              
              <p>
              <label for=""><strong> * </strong>Correo Electrónico</label>
              <input type="email" id="va_email" name="va_email" placeholder="Ingrese un correo electrónico">
              </p>
              <p>
              <label for=""><strong> * </strong>Password</label>
              <input type="password" id="va_contrasena" name="va_contrasena" placeholder="Ingrese un password">
              </p>
              <p>
              <label for=""><strong> * </strong>Confirmar Password</label>
              <input type="password" id="va_contrasena2" name="va_contrasena2" placeholder="Confirme su password">
              </p>
              <input type="submit" value="Registrarse">
          </form>
      </div>
    </div>
  </div> <!-- #main -->
</div> <!-- #main-container -->
   
