<div class="main-container">
    <div class="container">
       
       
        <div class="row-fluid">
			<div ><?php echo $this->valor;  ?></div> 
    		<div class="row-fluid">       
                <div class="span12 contenido-cuenta">
                    <div class="row-fluid">
                    <div class="span6 cuenta misdatos">
                        <div class="ocultar">
                        	<i class="icon-datos ico-noti"></i>
                                 <?php if ($_GET['m']==1) { ?> <p><?php echo 'datos cambiados correctamente'?></p> <?php } ?>
                        	<p id="datos">ACTUALIZAR MIS DATOS</p>
                        </div>
                        <span>x</span>
                    	<div class="modificardatos">
                                        <?php
                            $usuario = $this->usuario;
                            $form = $this->form;
                            $form->setAttributes(array(
                                'action' => $this->url.'/usuario/index/editarusuario/'.$this->in_id,
                                'method' => 'post',
                                'class'=>'form-horizontal'
                            ));

                            $form->prepare();
                            echo $this->form()->openTag($form);
                            ?>
                         	<div class="actualizar">
                                    <?php echo $this->formHidden($form->get('in_id'));?>
		                        <h1>Actualizar Cuenta</h1>		                        
<!-- 		                        <form action="" id="actualizar"> -->
		                        	<h5>Cambiar mi imagen de perfil</h5>
		                        	<div class="cambiofoto2">
							        	<div class="fileupload fileupload-new" data-provides="fileupload">
								            <div class="img-thu-user fileupload-new thumbnail">
                                                <?php if(($this->usuario->va_foto)!="foto-carnet.jpg"){?>
                                                    <img src="<?php echo $this->host('images') ?>/usuario/general/<?php echo $this->usuario->va_foto ;?>" style="width:130px;height:130px;">
                                                <?php }else{?>
                                                    <img src="<?php echo $this->host('images') ?>/img/foto-carnet.jpg" style="width:130px;height:130px;">
                                                <?php }?>
								            </div>
							            	<div class="img-thu-user fileupload-preview fileupload-exists thumbnail" style="height: 130px;"></div>
								            <div class="detalle-img">
								              	<strong class="btn-file">
									              	<strong class="btn fileupload-new">Cargar una imagen</strong>
									              	<strong class="btn fileupload-exists">Cambiar Imagen </strong>
									               	<input type="file" name="va_foto" class="" id="va_foto">              
								               	</strong>
								              	<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remover</a>         
								            </div>
							          	</div>
							        </div>
		                        	<h5>Mis datos personales </h5>
		                            <p>
		                            	<label for="">Nombre Completo</label>
                                        <?php echo $this->formRow($form->get('va_nombre'));?>
		                            </p>                         
		                            <p>
		                            	<label for="">Correo Electrónico</label>
                                        <?php echo $this->formRow($form->get('va_email'));?>
		                            </p>                                  
		                             <p>
		                            	<label for="">Documento de Identidad</label>
                                        <?php echo $this->formRow($form->get('va_dni'));?>
		                            </p>
		                            <p>
                                        <label for="">Género</label>
                                                
                                        <?php if (($this->usuario->va_genero)==''){ ?>
                                            <label for="">Seleccionar un género</label>
                                        <?php   }?>
                                            
                                        <?php echo $this->formRow($form->get('va_genero'));?>
 
		                            </p>
		                            <h5>Mis Intereses </h5>
		                            <div class="int">
		                              	<label for="">Ingresar Intereses</label>
		                              	<?php echo $this->formRow($form->get('va_descripcion'));?>
	                              	</div>                               
		                            <p>
                                                <?php echo $this->formSubmit($form->get('submit'));?>
		                            </p>
		                             <?php echo $this->form()->closeTag();?> 
<!-- 		                        </form> -->
                    		    
                                </div> 
                        
                    	</div>                    
                    </div>
                    <div class="span6 cuenta noti">
	                    <div class="ocultarnoti">
	                    <i class="icon-noti ico-noti"></i>
	                    <p id="inoti">NOTIFICACIONES</p> 
	                    </div>
	                    <span>x</span>
	                    <div class="notificaciones">
	                                <?php
                            $formnotif = $this->formnotif;
                            
                            $formnotif->setAttributes(array(
                                'action' => $this->url.'/usuario/index/notificar',
                                'method' => 'post',
                                'class'=>'form-horizontal'
                            ));

                            $formnotif->prepare();
                            echo $this->form()->openTag($formnotif);
                            ?>
<!-- 	                        <form action="" id="notificaciones">  -->
	                        <h3>Notificaciones</h3>
	                        <?php echo $this->formRow($formnotif->get('tipo_notificacion'));?>                           

	                        <?php echo $this->formSubmit($formnotif->get('submit'));?>
	                         <?php echo $this->form()->closeTag();?> 
<!-- 	                        </form> -->
	                    </div>                   
	                </div>
            </div>                                   
           </div>
    	</div>  
           
        </div>
    </div> <!-- #main -->
</div> <!-- #main-container -->

  
  
