<div class="main-container">
    <div class="container">
        <div class="row-fluid">
            <?php
                            $usuario = $this->usuario;
                            $form = $this->form;
                            $form->setAttributes(array(
                                'action' => $this->url.'/usuario/index/editarusuario/'.$this->in_id,
                                'method' => 'post',
                                'class'=>'form-horizontal'
                            ));

                            $form->prepare();
                            echo $this->form()->openTag($form);
                            ?>
<!--            <div class="span12 menu-login">
                <img src="http://lorempixel.com/50/50/people/" alt="" class="img-user"> <span>Bienvenido <?php echo $this->usuario->va_nombre?></span>
                <div class="logincuenta">
                <ul>
                    <li><i class="icon-group"> </i> <a href="usuario.html" >Mis Grupos</a> </li>
                    <li><i class="icon-cuenta"></i> <a href="usuario-cuenta.html" class="activomenu">Mi cuenta</a></li>
                    <li><i class="icon-salir"></i><a href="">Cerrar Sesion</a></li>                   
                </ul> 
                </div>                            
            </div>-->
			<div ><?php echo $this->valor;  ?></div> 
    		<div class="row-fluid">       
                <div class="span12 contenido-cuenta">
                    <div class="row-fluid">
                    <div class="span6 cuenta misdatos">
                        <div class="ocultar">
                        	<i class="icon-datos"></i>
                        	<p id="datos">ACTUALIZAR MI DATOS</p>
                        </div>
                        <span>x</span>
                    	<div class="modificardatos">
                            
                         	<div class="actualizar">
                                    <?php echo $this->formHidden($form->get('in_id'));?>
		                        <h1>Actualizar Cuenta</h1>		                        
		                        <form action="" id="actualizar">
		                        	<h5>Cambiar mi imagen de perfil</h5>
		                        	<div class="cambiofoto2">
							        	<div class="fileupload fileupload-new" data-provides="fileupload">
								            <div class="img-thu-user fileupload-new thumbnail">
                                                                                <?php if(($this->usuario->va_foto)!=""){?>
                                                                                    <img src="/imagenes/usuario/general/<?php echo $this->usuario->va_foto?>" style="width:130px;height:130px;">
                                                                                <?php }else{?>
                                                                                    <img src="/img/foto-carnet.jpg" style="width:130px;height:130px;">
                                                                                <?php }?>
								            </div>
							            	<div class="img-thu-user fileupload-preview fileupload-exists thumbnail" style="height: 130px;"></div>
								            <div class="detalle-img">
								              	<strong class="btn-file">
									              	<strong class="btn fileupload-new">Cargar una imagen</strong>
									              	<strong class="btn fileupload-exists">Cambiar Imagen </strong>
									               	<input type="file" name="va_foto" class="" id="va_foto">              
								               	</strong>
								              	<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remover</a>         
								            </div>
							          	</div>
							        </div>
		                        	<h5>Mis datos personales </h5>
		                            <p>
		                            	<label for="">Nombre Completo</label>
                                                
                                                <?php echo $this->formRow($form->get('va_nombre'));?>
                                                
<!--		                            	<input type="text" id="va_nombre" name="va_nombre" >-->
		                            </p>                         
		                            <p>
		                            	<label for="">Correo Electrónico</label>
                                                <?php echo $this->formRow($form->get('va_email'));?>
<!--		                            	<input type="email" id="va_email" name="va_email" >-->
		                            </p>                                  
		                             <p>
		                            	<label for="">Documento de Identidad</label>
                                                <?php echo $this->formRow($form->get('va_dni'));?>
<!--		                            	<input type="text" id="dni" name="dni" >-->
		                            </p>
		                            <p>
                                                <label for="">Género</label>
                                                
                                                <?php if (($this->usuario->va_genero)==''){ ?>
                                                    <label for="">Seleccionar un género</label>
                                                <?php   }?>
                                                    
                                                <?php echo $this->formRow($form->get('va_genero'));?>
                                                
                                                    
                                              
                                                
			                           
			                            
		                            </p>
<!--		                            <p>
			                            <label for="">Ciudad</label>
			                            <select name="" id="">
			                                <option value="">Barranco</option>
			                                <option value="">Miraflores</option>
			                            </select>
		                            </p>-->
		                            <h5>Mis Intereses </h5>
		                            <div class="int">
		                              	<label for="">Ingresar Intereses</label>
		                              	<?php echo $this->formRow($form->get('va_descripcion'));?>
<!--                                                <textarea name="" id="" cols="20" rows="4">
                                                
                                                </textarea>-->
	                              	</div>                               
		                            <p>

<!--		                            	<input type="submit" value="Actualizar">-->
                                                <?php echo $this->formSubmit($form->get('submit'));?>

<!--		                            	<input type="submit" class="btn btn-primary" value="Actualizar">-->

		                            </p>
		                        </form>
                    		    
                                </div> 
                        
                    	</div>                    
                    </div>
                    <div class="span6 cuenta noti">
	                    <div class="ocultarnoti">
	                    <i class="icon-noti"></i>
	                    <p id="inoti">NOTIFICACIONES</p> 
	                    </div>
	                    <span>x</span>
	                    <div class="notificaciones">
	                        <form action="" id="notificaciones"> 
	                        <h3>Notificaciones</h3>                           
	                            <label for="">
	                            <input type="checkbox" name="noti" id="noti">
	                            Recibir avisos por email cuando ingresa al Grupo 
	                            </label>
	                             <label for="">
	                            <input type="checkbox" name="noti" id="noti">
	                            Recibir avisos por email cuando sale del Grupo 
	                            </label> 
	                        <input type="submit" value="Enviar">                           
	                        </form>
	                    </div>                   
	                </div>
                <!--<div class="span6 cuenta mifoto">
                    <div class="ocultarfoto">
                    <i class="icon-foto"></i>
                    <p id="afoto">ACTUALIZAR MI FOTO</p>
                    </div>
                     <span>x</span>
                     <div class="cambiofoto">
                      <div class="fileupload fileupload-new" data-provides="fileupload" >
                        <div class="img-thu fileupload-new thumbnail">
                               <img src="img/foto-carnet.jpg" style="width:130px;height:130px;">
                            </div>
                    <div class="img-thu fileupload-preview fileupload-exists thumbnail" style="height: 130px;"></div>
                             <div class="detalle-img">
                      <strong class="boton btn-file">
                    <strong class="fileupload-new">Seleccione imagen</strong>
                <strong class="fileupload-exists">Cambiar</strong><input type="file" name='imagefile' /></strong>
                <a href="#" class="boton-rem fileupload-exists" data-dismiss="fileupload">Remover</a>                 
                                            </div>
                                        </div>
                     </div>                       
                </div>-->
            </div>                                   
           </div>
    	</div>  
           <?php echo $this->form()->closeTag();?>  
        </div>
    </div> <!-- #main -->
</div> <!-- #main-container -->

  
  
