<link rel="stylesheet" type="text/css" href="<?php echo $this->host('ruta')?>/js/select/select2.css">
<script type="text/javascript" src="<?php echo $this->host('ruta')?>/js/select/select2.min.js"></script>
<div class="main-container">
    <div class="container">
        <?php if ($_GET['m']==1) { ?>
            <div class="row-fluid">
                <div class="alert alert-success alert-margin alert-message">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <?php echo 'Datos guardados correctamente'?>
                </div>
            </div>
        <?php } ?>

			<?php echo $this->valor;  ?>
    		<div class="row-fluid"> 
                <div class="span12 dta-user contenido-cuenta box" style="margin-top:15px;">
                  <?php
                    $usuario = $this->usuario;
                    $form = $this->form;
                    $form->setAttributes(array(
                        'action' => $this->url . '/micuenta' ,//. $this->in_id
                        'method' => 'post',
                        'class' => 'form-horizontal usuario-actualizar',
                        'id' => 'editarusuario'
                    ));

                    $form->prepare();
                    echo $this->form()->openTag($form);
                    ?>
                        <h3>Datos generales</h3>
                        <div class="row-fluid">
                            <div class="span8">
                                <div class="control-group">
                                    <?php echo $this->formHidden($form->get('in_id'));?>
                                    <label class="control-label" for="va_nombre">Nombre: <span>*</span></label>
                                    <div class="controls">
                                        <?php echo $this->formRow($form->get('va_nombre'));?>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="va_email">Correo electrónico: <span>*</span></label>
                                    <div class="controls">
                                        <?php echo $this->formRow($form->get('va_email'));?>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="va_genero">Género:</label>
                                    <div class="controls">
                                        <?php echo $this->formRow($form->get('va_genero')); ?>
                                    </div>
                                </div>
                     
                                 <div class="control-group">
                                    <label class="control-label" for="pais">Pais:</label>
                                    <div class="controls">
                                         <?php echo $this->formRow($form->get('va_pais'));?>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="ta_ubigeo_in_id">Ciudad:</label>
                                    <div class="controls">
                                        <select id="ta_ubigeo_in_id"  name="ta_ubigeo_in_id" value=" "/>
                                        <?php if($this->nameCiudad ){?>
                                        <option value="<?php echo $this->nameID ; ?>"><?php echo $this->nameCiudad ; ?></option>
                                        <?php }else{?>
                                        <option value="">--- Seleccionar ---</option>
                                       <?php }?>
                                    </select>
                                    </div>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="control-group" style="overflow:hidden;">                                    
                                    <div class="controls" style="margin-left:0;">
                                        <div class="fileupload fileupload-new" data-provides="fileupload">
                                            <div class="img-thu-user fileupload-new thumbnail">
                                                <?php $valor = explode('/', $this->usuario->va_foto);
                                                if ($valor[0] == 'https:') { ?>  
                                                    <img src="<?php echo $this->usuario->va_foto; ?>?width=130&height=130">                                            
                                                <?php } else {
                                                    if (($this->usuario->va_foto) != "foto-carnet.jpg") { ?>
                                                        <img src="<?php echo $this->host('images') ?>/usuario/general/<?php echo $this->usuario->va_foto; ?>" style="width:130px;height:130px;">
                                                    <?php } else { ?>
                                                        <img src="<?php echo $this->host('img') ?>/foto-carnet.jpg" style="width:130px;height:130px;">
                                                    <?php }
                                                }
                                                ?>
                                            </div>
                                            <div class="img-thu-user fileupload-preview fileupload-exists thumbnail" style="height: 130px;"></div>
                                            <div class="detalle-img">
                                                <strong class="btn-file">
                                                    <strong class="btn fileupload-new">Cargar una imagen</strong>
                                                    <strong class="btn fileupload-exists">Cambiar Imagen </strong>
                                                    <input type="file" name="va_foto" class="" id="va_foto">              
                                                </strong>
                                                <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remover</a>         
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                        
                       <h3>Social Media</h3>
                        <div class="row-fluid">
                            <div class="span12">
                                <div class="control-group">
                                    <label class="control-label" for="va_facebook">Facebook:</label>
                                    <div class="controls">
                                        <?php echo $this->formRow($form->get('va_facebook'));?>
                                    </div>
                                 </div>
                                <div class="control-group">
                                    <label class="control-label" for="va_twitter">Twitter:</label>
                                    <div class="controls">
                                        <?php echo $this->formRow($form->get('va_twitter'));?>
                                    </div>
                                 </div>  
                                
                            </div>
                        </div>
                                                
                        <h3>Datos de interes</h3>
                        <div class="row-fluid">
                            <div class="span12">
                                <div class="control-group">
                                    <label class="control-label">Tus intereses:</label>
                                    <div class="controls">
                                        <?php echo $this->formRow($form->get('select2')); ?>
                                        <!--<select multiple id="e1" name="select2[]" style="width:97.3%;">
                                        </select>-->
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="span12">
                                <div class="control-group">
                                    <label class="control-label" for="va_descripcion">Mis intereses:</label>
                                    <div class="controls">
                                        <?php echo $this->formRow($form->get('va_descripcion'));?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <p class="crear-evento box"><?php echo $this->formSubmit($form->get('submit'));?>             </p>
                         <?php echo $this->form()->closeTag();?>   
                </div>
    	   </div>
            <div class="row-fluid">
                <div class="span12 notifi contenido-cuenta box" style="margin-top:15px;">
                    <h3>Tu configuración</h3>
                    <?php
                    $formnotif = $this->formnotif;

                    $formnotif->setAttributes(array(
                        'action' => $this->url . '/usuario/index/notificar',
                        'method' => 'post',
                        'class' => 'form-horizontal'
                    ));

                    $formnotif->prepare();
                    echo $this->form()->openTag($formnotif);
                    ?>     
                    <?php echo $this->formRow($formnotif->get('tipo_notificacion'));?>  
                    <p class="crear-evento box">
                         <?php echo $this->formSubmit($formnotif->get('submit'));?>                            
                    </p>
                    <?php echo $this->form()->closeTag();?>
            </div>
        </div>         
        </div>
    </div> <!-- #main -->
</div> <!-- #main-container -->

<script type="text/javascript">
    $(document).ready(function(){
        $(".alert-message").alert();
        window.setTimeout(function() { $(".alert-message").alert('close'); }, 7000);
        $("#e1").select2();

        var cboPais = $("#pais");
        var distriJ = $("#ta_ubigeo_in_id");
        cboPais.change(function(){
            var hi = cboPais.val();
            if(hi === ''){
                var inp = '<option value="">--- Seleccionar ---</option>';
                distriJ.empty();
                distriJ.append(inp);
            }else{
                var valPais =  $(this).find('option:selected').val();
                $.ajax({
                    url: "/usuario/index/jsonciudad?code=" + valPais , 
                    cache:true,
                    data: {},
                    success: function(nselect){
                        var data = JSON.parse(nselect || {});
                        var departList = [];
                        distriJ.empty();
                        for (var key in data) {
                            dataF = data[key];
                            var keyL = dataF.ID;
                            var val = dataF.Name;
                            var  departItem = '<option value="'+ keyL +'">'+ val +'</option>';
                            departList.push(departItem);
                        }
                        var joinDep = departList.join('');
                        distriJ.append(joinDep);
                    }
                });
            }
        });
    });
</script>
  
  
