<div class="main-container">
    <div class="container">
    	<div class="row-fluid">
        	<div class="span12 contenido-group">
        		<div class="row-fluid">
        			<?php echo $this->grupo; ?>
        		</div>
        		<div class="row-fluid mi-grupo">
        			<header class="span12"><span>Eventos donde participo</span> <div class="agrupos"><a href="<?php echo $this->url('elegir-grupo');?>">Crear nuevo evento</a></div></header>
        		</div>
				<div class="row-fluid">
					<div class="span12 main wrapper" id="content" data-ui-scrollbar>
	                    <ul>
	                  <?php  foreach ($this->eventos  as $eventos) :?>
                            <li data-category="web">
                                <a href="/evento/<?php echo $this->escapeHtml($eventos->id); ?>" class="preview" data-ui-lightbox>
                               <img src="<?php   echo $this->host('images') . '/eventos/general/' . htmlspecialchars($eventos->imagen, ENT_QUOTES, 'utf-8');  ?>">
                                </a>
                                <div class="content">
                                	<div class="entry-post-date" style="border-top-color: #2999b5">
		                                <div class="date-month">
		                                    <?php  $fecha = date_create($eventos->fecha);
                                         echo $fecha = date_format($fecha, 'd/m/Y'); ?>
		                                </div>
		                            </div>
                                    <h2>
                                        <a href="/evento/<?php echo $this->escapeHtml($eventos->id); ?>"><?php echo $this->escapeHtml($eventos->nombre); ?></a>
                                    </h2>
                                    <div class="divider-1px-meta"></div>
		                            <footer class="entry-extra clearfix">
		                                <span class="meta-comments">
		                                    <i class="icon-comment"></i>
		                                    <a href="#" title="comentarios"><?php echo  $this->escapeHtml($eventos->comentarios);?></a>
		                                </span><!-- .meta-comments -->
		                                <span class="meta-views" title="Views">
		                                    <i class="icon-tag"></i>
		                                    <a href="#" title="Categoría"><?php echo  $this->escapeHtml($eventos->nombre_categoria);?></a>
		                                </span><!-- .meta-views -->
		                            </footer>
                                </div>
                            </li>
                            <?php endforeach;?>

	                    </ul>               
	                </div> 
				</div>
              <!--  <div class="row-fluid">
                	<header class="span12"><span>Grupos Similares</span></header>
                </div>
				<div class="row-fluid">
					<div class="span12 main wrapper" id="content" data-ui-scrollbar>
		                <ul>
		                  
		                    <li data-category="web">
		                        <a href="#" class="preview" data-ui-lightbox>
		                            <img src="../../img/eventos/1.jpg" alt=""/>
		                        </a>
		                        <div class="content">
		                            <div class="info">
		                                <span>2013</span>
		                                <span class="category"><a href="#">Web</a></span>
		                            </div>
		                            <h2><a href="#">Tumidei Spa</a></h2>
		                            <p>
		                                Corporate web site. Html5. Responsive.
		                            </p>
		                        </div>
		                    </li>
		                    

		                    <li data-category="art">
		                        <a href="#" class="preview" data-ui-lightbox>
		                            <img src="../../img/eventos/2.jpg" alt=""/>
		                        </a>
		                        <div class="content">
		                            <div class="info">
		                                <span>2013</span>
		                                <span class="category"><a href="#">Art</a></span>
		                            </div>
		                            <h2><a href="#">Crazy Home</a></h2>
		                            <p>
		                                Overdrive realizza Art Image (quadri e mobili d'arredo) in collaborazione con Crazy Home.
		                            </p>
		                        </div>
		                    </li>  

		                     
		                    <li data-category="foto">
		                         <a href="#" class="preview" data-ui-lightbox>
		                            <img src="../../img/eventos/3.jpg" alt=""/>
		                        </a>
		                        <div class="content">
		                            <div class="info">
		                                <span>2013</span>
		                                <span class="category"><a href="#">Lo Studio</a></span>
		                            </div>
		                            <h2><a href="#">Overdrive</a></h2>
		                            <p>
		                                I nostro Quartier Generale. Lissone. Piazzale Giotto 1.
		                            </p>
		                        </div>
		                    </li> 
		            	</ul>               
		    		</div>
				</div>-->
	    </div>
    </div>
  </div>
</div>
