<div class="main-container">
    <div class="container">
    	<div class="row-fluid">
        	<div class="span12 contenido-group">
        		<div class="row-fluid">
        			<?php echo $this->grupo; ?>
        		</div>
        		<div class="row-fluid mi-grupo">
        			<header class="span12"><span>Grupos donde participo</span> <div class="agrupos"><a href="crear-evento.html">Crear nuevo Grupo</a></div></header>
        		</div>
				<div class="row-fluid">
					<div class="span12 main wrapper" id="content" data-ui-scrollbar>
	                    <ul>
                               <?php  foreach ($this->grupospertenece  as $grupospertenece) :?>
	                        <li data-category="web">
	                            <a href="/grupo/index/detallegrupo?id=<?php echo $this->escapeHtml($grupospertenece->id); ?>" class="preview" data-ui-lightbox>
	                                <img src="<?php   echo $this->host('images') . '/grupos/general/' . htmlspecialchars($grupospertenece->imagen, ENT_QUOTES, 'utf-8');  ?>" alt=""/>
	                            </a>
	                            <div class="content">
	                                <div class="info">
	                                    <span><?php  $fecha = date_create($this->escapeHtml($grupospertenece->fecha));
                                         echo $fecha = date_format($fecha, "d \d\e\l m \d\e\l Y"); ?></span>
	                                    <span class="category"><a href="#"><?php echo  $this->escapeHtml($grupospertenece->nombre_categoria);?></a></span>
	                                </div>
	                                <h2><a href="/grupo/index/detallegrupo?id=<?php echo $this->escapeHtml($grupospertenece->id); ?>"><?php echo  $this->escapeHtml($grupospertenece->nombre);?></a></h2>
	                                <p>
	                          <?php echo $this->escapeHtml($grupospertenece->descripcion); ?>
	                                </p>
	                            </div>
	                        </li>
	                    <?php endforeach;  ?>
	                    </ul>               
	                </div> 
				</div>
                <div class="row-fluid">
                	<header class="span12"><span>Grupos Similares</span></header>
                </div>
				<div class="row-fluid">
					<div class="span12 main wrapper" id="content" data-ui-scrollbar>
		                <ul>
		                     <?php  foreach ($this->otrosgrupos  as $otrosgrupos) :?>
	                        <li data-category="web">
	                            <a href="/grupo/index/detallegrupo?id=<?php echo $this->escapeHtml($otrosgrupos->id); ?>" class="preview" data-ui-lightbox>
	                                <img src="<?php   echo $this->host('images') . '/grupos/general/' . htmlspecialchars($otrosgrupos->va_imagen, ENT_QUOTES, 'utf-8');  ?>" alt=""/>
	                            </a>
	                            <div class="content">
	                                <div class="info">
	                                    <span><?php  $fecha = date_create($this->escapeHtml($otrosgrupos->fecha));
                                         echo $fecha = date_format($fecha, "d \d\e\l m \d\e\l Y"); ?></span>
	                                    <span class="category"><a href="#"><?php echo  $this->escapeHtml($otrosgrupos->nombre_categoria_similar);?></a></span>
	                                </div>
	                                <h2><a href="/grupo/index/detallegrupo?id=<?php echo $this->escapeHtml($otrosgrupos->in_id); ?>"><?php echo  $this->escapeHtml($otrosgrupos->va_nombre);?></a></h2>
	                                <p>
	                          <?php echo $this->escapeHtml($otrosgrupos->va_descripcion); ?>
	                                </p>
	                            </div>
	                        </li>
	                    <?php endforeach;  ?>
		             

		            	</ul>               
		    		</div>
				</div>
	    </div>
    </div>
  </div>
</div>


