<div class="span12 menu-login">
    <img src="http://lorempixel.com/50/50/people/" alt="" class="img-user"> <span>Bienvenido Usuario</span>
    <div class="logincuenta">
    <ul>
        <li><i class="icon-group"> </i> <a href="usuario.html" >Mis Grupos</a> </li>
        <li><i class="icon-cuenta"></i> <a href="usuario-cuenta.html" class="activomenu">Mi cuenta</a></li>
        <li><i class="icon-salir"></i><a href="">Cerrar Sesion</a></li>                   
    </ul> 
    </div>                            
</div>