<div class="main-container">
    <div class="container">
        <?php if ($this->mensaje) { ?> <div class="row-fluid">
      <div class="alert alert-margin">
        <?php  echo $this->mensaje; ?>
      </div>
    </div> <?php } ?>
    	<div class="row-fluid">
        	<div class="span12 contenido-group">
        		<div class="row-fluid">
        			<?php echo $this->grupo; ?>
        		</div>
        		<div class="row-fluid mi-grupo">
        			<header class="span12"><span>Mis Eventos</span> <div class="agrupos"><a href="<?php echo $this->url('elegir-grupo');?>">Crear nuevo evento</a></div></header>
        		</div>
				<div class="row-fluid">
					<div class="span12 main wrapper" data-ui-scrollbar>
						<div id="content">
		                    <?php  foreach ($this->miseventos  as $miseventos) :?>  
		                    <article id="post-9" class="img-dev-evento post-9 post type-post status-publish format-standard sticky hentry category-beauty tag-portrait tag-sexy tag-woman tag-young masonry-box clearfix" itemscope itemtype="http://schema.org/BlogPosting">
		                        <div class="post-block three_columns">
		                            <div class="entry-thumb">
		                                <a href="<?php echo $this->host('base').$this->url('evento').'/'.$this->escapeHtml($miseventos->in_id); ?>" class="preview" data-ui-lightbox>
			                                <img class="img-cart" src="<?php   echo $this->host('images') . '/eventos/general/' . htmlspecialchars($miseventos->va_imagen, ENT_QUOTES, 'utf-8');  ?>" alt=""/>
			                            </a>
			                            <?php if($this->eventos[0]['ta_usuario_in_id']==$session->in_id){?>
						                    <div class="content-edit">                             
						                      <a href="<?php echo $this->host('base').$this->url('editar-evento').'/'.$this->escapeHtml($miseventos->in_id);?>" title="Editar detalle de evento">
						                        <img src="/img/edit-2.png">
						                      </a>
						                    </div>
						                <?php } ?>
		                            </div> <!-- .entry-thumb -->
		                            <div class="content">
		                                <div class="entry-post-date" style="border-top-color: #2999b5">
		                                    <div class="date-month">
		                                        <?php  $fecha = date_create($eventos->va_fecha);
		                                        echo $fecha = date_format($fecha, 'd/m/Y'); ?>                     
		                                      </div>
		                                </div>
		                                <h2>
		                                	<a href="<?php echo $this->host('base').$this->url('evento').'/'.$this->escapeHtml($miseventos->in_id); ?>"><?php echo  $this->escapeHtml($miseventos->va_nombre);?></a>
		                                </h2>
		                                <div class="divider-1px-meta"></div>
		                                <footer class="entry-extra clearfix">
		                                    <span class="meta-comments">
			                                    <i class="icon-comment"></i>
			                                    <a href="#" title="comentarios"><?php echo  $this->escapeHtml($miseventos->comentarios);?></a>
			                                </span><!-- .meta-comments -->
			                                <span class="meta-views" title="Views">
			                                    <i class="icon-tag"></i>
			                                    <a href="#" title="Categoría"><?php echo  $this->escapeHtml($miseventos->nombre_categoria);?></a>
			                                </span><!-- .meta-views -->
		                                </footer>
		                            </div>
		                        </div> <!-- .post-block -->  
		                    </article><!-- #post-ID -->
		                    <?php endforeach; ?>-->
		                </div>              
	                </div> 
				</div>
             
	    </div>
    </div>
        
        <div class="row-fluid">
            <div class="span12" id="pagina">
                <?php echo (count($this->miseventos)> 0)?$this->paginationControl($this->miseventos, 'Sliding', 'grupo/evento/paginador.phtml',array('variable'=>'/cuenta/miseventos?')):""; ?>
            </div>
        </div> 
        
        
  </div>
</div>
<script type="text/javascript">
            /* <![CDATA[ */

            // Masonry
            jQuery.noConflict()(function($){
                //$(window).load(function() {
        $(document).ready(function() {
            var $container = $('#content');

            $container.imagesLoaded(function(){
              $container.masonry({
                itemSelector: '.masonry-box',
                isAnimated: true
              });
            });

            // Infinite Scroll

            $container.infinitescroll({
                navSelector  : '.pagination',    // selector for the paged navigation 
                nextSelector : '.pagination a',  // selector for the NEXT link (to page 2)
                itemSelector : '.masonry-box',     // selector for all items you'll retrieve
                loading: {
                    finishedMsg: 'No more posts to load.',
                    img: 'http://wp.color-theme.com/pravda/wp-content/themes/wp-pravda/img/ajax-loader.gif'
                }
            },

            // trigger Masonry as a callback
            function(newElements) {
                var $newElems = $( newElements ).css({ opacity: 0 });

                $newElems.imagesLoaded(function()   {
                    $newElems.animate({ opacity: 1 });
                    $container.masonry( 'appended', $newElems, true ); 

                    // post like system
                    $(".post-like a").click(function() {

                        heart = $(this);
                        post_id = heart.data("post_id");

                        $.ajax({
                                type: "post",
                                url: ajax_var.url,
                                data: "action=post-like&nonce="+ajax_var.nonce+"&post_like=&post_id="+post_id,
                                success: function(count){
                                    if(count != "already") {
                                        heart.addClass("voted");
                                        heart.siblings(".count").text(count);
                                    }
                                }
                        });
                        return false;
                    }) // end post like system

                });
            });
         
            });
        });
        /* ]]> */   
            </script>


