<div class="main-container">
    <div class="container">
    	<div class="row-fluid">
        	<div class="span12 contenido-group">
        		<div class="row-fluid">
        			<?php echo $this->grupo; ?>
        		</div>
        		<div class="row-fluid mi-grupo">
        			<header class="span12"><span>Mis Grupos</span> <div class="agrupos"><a href="crear-evento.html">Crear nuevo Grupo</a></div></header>
        		</div>
				<div class="row-fluid">
					<div class="span12 main wrapper" id="content" data-ui-scrollbar>
	                    <ul>
	                      <?php  foreach ($this->misgrupos  as $misgrupos) :?>
	                        <li data-category="web">
	                            <a href="/grupo/index/detallegrupo?id=<?php echo $this->escapeHtml($misgrupos->in_id); ?>" class="preview" data-ui-lightbox>
	                                <img src="<?php   echo $this->host('images') . '/grupos/general/' . htmlspecialchars($misgrupos->va_imagen, ENT_QUOTES, 'utf-8');  ?>" alt=""/>
	                            </a>
	                            <div class="content">
	                                <div class="info">
	                                    <span><?php  $fecha = date_create($misgrupos->va_fecha);
                                         echo $fecha = date_format($fecha, 'd/m/Y'); ?></span>
	                                    <span class="category"><a href="#"> <?php echo  $this->escapeHtml($misgrupos->nombre_categoria);?></a></span>
	                                </div>
	                                <h2><a href="/grupo/index/detallegrupo?id=<?php echo $this->escapeHtml($misgrupos->in_id); ?>"><?php echo  $this->escapeHtml($misgrupos->va_nombre);?></a></h2>
	                                <p>
	                                    <?php echo  $this->escapeHtml($misgrupos->va_descripcion);?>
	                                </p>
	                            </div>
	                        </li>
	                       
	                  <?php endforeach;  ?>

	                    </ul>               
	                </div> 
				</div>
             
	    </div>
    </div>
  </div>
</div>