<div class="main-container">
    <div class="container">
    	<div class="row-fluid">
    		<div class="span12 group-sidebar event-group">
    			<div class="row-fluid">
    				<div class="span8 contenido-perfil-usuario">
    					<h2><?php echo ucwords($this->usuario->va_nombre);?></h2>
                                        <?php  if($this->usuario->va_pais){  ?>
                                        <h5>Pais:</h5>
                                        <span><?php echo ucwords($this->usuario->va_pais);?></span>
    					<h5>Ciudad:</h5>
                                        <span><?php echo ucwords($this->usuario->ta_ubigeo_in_id);?></span>
                                        
                                        <?php  }  ?>
    					<div class="row-fluid">
    						<div class="span12 title-miembro">
    							<h4>Miembro desde:</h4>
                                  <span><?php
                                    $fecha = date_create($this->escapeHtml($this->usuario->va_fecha_ingreso));
                                    $arrayMeses = array('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                                        'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
                                    echo date_format($fecha, "d") . ' de ' . $arrayMeses[date('m') - 1] . ' del ' . date_format($fecha, "Y");
                                    ?></span>
    						</div>
    					</div>
                                        <?php if($this->usuario->va_facebook || $this->usuario->va_twitter){ ?>
    					<h4>Redes sociales</h4>
    					<div class="social-net">
    						<ul>
    							<?php if($this->usuario->va_facebook){?><li class="facebook-dev"><a href="http://www.facebook.com/<?php echo $this->usuario->va_facebook;?>" target="_blank"></a></li><?php }?>
    							<?php if($this->usuario->va_twitter){?><li class="twitter-dev"><a href="http://www.twitter.com/<?php echo $this->usuario->va_twitter;?>" target="_blank"></a></li><?php }?>
    						</ul>
    					</div>
                                        <?php } ?>
    					
                                      <?php if($this->usuario->va_descripcion!='0') { ?>  
                                        <p>
                                                <?php echo $this->usuario->va_descripcion;?>
<!--    						What is your business?, Aún no hay respuestas. What do you need to take your business to the next level?, Aún no hay respuestas. Who told you about us? Google? Yahoo? Homer Simpson? We ask so we can give them credit. Thank you in advance.-->
    					</p><?php  }  ?> 
    				</div>
    				<div class="span4">
    					<div class="img-grupo" style="margin-bottom:15px;padding:0;">
                                            
                                      <?php $valor = explode('/',$this->usuario->va_foto);
                                    if($valor[0]=='https:'){ ?>  
                                        <img src="<?php echo $this->usuario->va_foto ;?>">                                            
                                    <?php } else {
                                        if(($this->usuario->va_foto)!="foto-carnet.jpg"){?>
                                            <img src="<?php echo $this->host('images') ?>/usuario/principal/<?php echo $this->usuario->va_foto ;?>" >
                                        <?php }else{?>
                                            <img src="<?php echo $this->host('img') ?>/foto-carnet.jpg">
                                        <?php } 
                                    }?>           

			            </div>
			            <div class="content-grup-j">
			            	<h3>MIEMBRO DE <?php echo $this->mienbros->count()?> GRUPOS</h3>
			            	<ul>
                                            <?php foreach($this->mienbros as $mienbro){ ?>
                                <li id="user-<?php echo $mienbro->ta_usuario_in_id;?>">
		                            <div class="users">
		                                <div class="row-fluid">
		                                    <div class="span3 img-user-ev">
		                                    	<img src="<?php echo $this->host('images')?>/grupos/general/<?php echo $mienbro->imagen;?>">
		                                    </div>
		                                    <div class="span9 desc-user">
		                                        <h5><a href="<?php echo $this->url('detalle-grupo')?>/<?php echo $mienbro->ta_grupo_in_id;?>"><?php echo $mienbro->nombre_grupo;?></a></h5>
		                                        <!--<p>co-fundador</p>-->
		                                    </div>
		                                </div>
		                            </div>
                            	</li>
                                <?php } ?>
                            </ul>
			            </div>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</div>