<div class="main-container">
    <div class="container">
    	<div class="row-fluid">
    		<div class="span12 group-sidebar event-group">
    			<div class="row-fluid">
    				<div class="span8 contenido-perfil-usuario">
    					<h2>Jesser pariona huarcaya</h2>
    					<h5>Organizador</h5>
    					<div class="row-fluid">
    						<div class="span12 title-miembro">
    							<h4>Miembro desde:</h4>
    							<span>6 de mayo de 2012</span>
    						</div>
    					</div>
    					<h4>Redes sociales</h4>
    					<div class="social-net">
    						<ul>
    							<li class="facebook-dev"><a href="http://www.facebook.com/" target="_blank"></a></li>
    							<li class="twitter-dev"><a href="http://www.twitter.com/" target="_blank"></a></li>
    						</ul>
    					</div>
    					<p>
    						What is your business?, Aún no hay respuestas. What do you need to take your business to the next level?, Aún no hay respuestas. Who told you about us? Google? Yahoo? Homer Simpson? We ask so we can give them credit. Thank you in advance.
    					</p>
    				</div>
    				<div class="span4">
    					<div class="img-grupo" style="margin-bottom:15px;padding:0;">
			                <img src="/img/la-hora-loca.jpg">
			            </div>
			            <div class="content-grup-j">
			            	<h3>MIEMBRO DE 4 GRUPOS</h3>
			            	<ul>
                                <li id="user-182">
		                            <div class="users">
		                                <div class="row-fluid">
		                                    <div class="span3 img-user-ev">
		                                    	<img src=" http://192.168.1.25:8081/imagenes/usuario/detalle/jesser-pariona-huarcaya-5227ba8650875.jpg">
		                                    </div>
		                                    <div class="span9 desc-user">
		                                        <h5><a href="#">Grupo de los mas</a></h5>
		                                        <p>co-fundador</p>
		                                    </div>
		                                </div>
		                            </div>
                            	</li>
                                <li id="user-141">
                            		<div class="users">
		                                <div class="row-fluid">
		                                    <div class="span3 img-user-ev">
		                                        <img src="http://192.168.1.25:8081/imagenes/usuario/detalle/-521641b93321a.jpg">	                                          
		                                    </div>
		                                    <div class="span9 desc-user">
		                                        <h5><a href="#">Grupo de los mas mas</a></h5>
		                                        <p>miembro</p>
		                                    </div>
		                                </div>
	                                </div>
                            	</li>
                            </ul>
			            </div>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</div>