		<div class="main-container">
            <div class="container">
                <!--Crear Grupo-->
                <div class="row-fluid elige-crea">
                    <div class="crear-grupo-agregar">
                        <div class="row-fluid">
                            <div class="span12 crear-evento event">
                                <h1>Elige tu grupo o crea un nuevo grupo</h1>
                                <p>¡Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy!</p>
                            </div>
                        </div>
                        <div class="row-fluid event nmb">
                            <div class="span12 space-group">
                                <label>Elige tu grupo:</label>
                                 <select name="grupos" class="span11 nm-crear-grupo" id="crearGrupo">
                                    <option value="" label="..Elige un grupo..">..Elige un grupo..</option>
                                <?php foreach($this->grupos as $grupo): ?>
                                    <option value="<?php echo $grupo['ta_grupo_in_id'];?>" label="<?php echo $grupo['nom_grup'];?>"><?php echo $grupo['nom_grup'];?></option>
                                <?php endforeach; ?>
                               </select>
                            </div>
                            <p class="activar-agregar" style="margin-top:10px;margin-left:10px;">
                                <a href="#" class="btn btn-primary btn-agregar">Agregar un nuevo grupo</a>
                            </p>
                        </div>
                    </div><!--Crear grupo o agregar-->
                    <p class="next-space" style="display:none;">
                        <a href="#" class="btn btn-warning next-grupo">Siguiente</a>
                    </p>
                </div>    
                <div class="row-fluid crear-grupos" style="display:none;">
                    <?php
                    $form = $this->form;

                    $form->setAttributes(array(
                        'action' => $this->url.'/grupo/index/agregargrupo',
                        'method' => 'post',
                        'class'=>'span12 form-crear-grupo',
                        'id'=>'crear-group'
                    ));

                    $form->prepare();
                    echo $this->form()->openTag($form);
                    ?>
                    <!--<form action="" class="span12 form-crear-grupo" id="crear-group">-->
                        <div class="row-fluid">
                            <div class="span12 crear-evento event">
                                <h1>Crear tu grupo</h1>
                                <p>¡Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy!</p>
                            </div>
                        </div>
                        <div class="row-fluid event nmb">
                            <div class="span8 space-group">
                                <?php echo $this->formHidden($form->get('in_id'));?>
                                <?php echo $this->formRow($form->get('va_nombre'));?>
                                <?php echo $this->formRow($form->get('ta_categoria_in_id'));?>
                                <?php echo $this->formRow($form->get('va_descripcion'));?>
                            </div>
                            <div class="span4 space-group">
                                <div class="control-group">
                                    <label for="textfield" class="control-label"></label>
                                    <div class="controls">
                                        <div class="fileupload fileupload-new" data-provides="fileupload">
                                            <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
                                                <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" />
                                            </div>
                                            <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                                            <div>
                                                <span class="btn btn-file"><span class="fileupload-new">Select image</span><span class="fileupload-exists">Change</span>
                                                   <?php echo $this->formRow($form->get('va_imagen'));?></span>
                                                <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <p class="crear-evento">
                            <?php echo $this->formSubmit($form->get('submit'));?>
                            <a href="#" class="btn btn-inverse btn-cancelar">Cancelar</a>
                        </p>
                    <!--</form>-->
                    <?php echo $this->form()->closeTag();?>
                </div>        
                <div class="row-fluid crear-evento-grupos" style="display:none;">
                    <form action="" class="span12 form-crear-grupo" id="crearEventoG">
                        <input type="hidden" name="grupoEvento" value="">
                        <div class="row-fluid">
                            <div class="span12 crear-evento event">
                                <h1>Crear un nuevo evento</h1>
                                <p>¡Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy!</p>
                            </div>
                        </div>
                        <div class="row-fluid crear-evento-1 event">
                            <h2>Describe tu actividad</h2>
                            <div class="span8 desc-evento">
                                <label>Nombre del evento:</label>
                                <input type="text" name="evento" placeholder="Ingrese el nombre del evento…" class="span12"> 
                                
                                <label>Descripción del evento:</label>
                                <textarea class="ckeditor" cols="80" id="editor1" name="editor1" rows="10"></textarea>
                            </div>
                            <div class="span4">
                                <div class="control-group">
                                    <label for="textfield" class="control-label"></label>
                                    <div class="controls">
                                        <div class="fileupload fileupload-new" data-provides="fileupload">
                                            <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
                                                <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" />
                                            </div>
                                            <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                                            <div>
                                                <span class="btn btn-file"><span class="fileupload-new">Select image</span><span class="fileupload-exists">Change</span><input type="file" name='imagefile' /></span>
                                                <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row-fluid crear-evento-2 event">
                            <h2>Cuando? y Cuanto sera el precio.</h2>
                            <div class="span3 fecha event-padding">
                                <div class="form_row">
                                    <label class="field_name">Fecha y hora:</label>
                                    <div class="field">
                                        <div class="span10 input-append date form_datetime2" data-date="2013-02-21T15:25:00Z">
                                            <input size="16" type="text" value="" readonly class="span10">
                                            <span class="add-on"><i class="icon-remove"></i></span>
                                            <span class="add-on"><i class="icon-calendar"></i></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="span3">
                                <label class="field_name">Duración del evento:</label>
                                <div class="input-prepend input-append">
                                    <span class="add-on"><i class="icon-time"></i></span>
                                    <input class="span6" id="inputCosto" type="text">
                                    <span class="add-on">Horas</span>
                                </div>
                            </div>
                            <div class="span3">
                                <label class="field_name">Precio referencial para el evento:</label>
                                <div class="input-prepend input-append">
                                    <span class="add-on">S/.</span>
                                    <input class="span6" id="inputCosto" type="text">
                                    <span class="add-on">.00</span>
                                </div>
                            </div>
                            <div class="span3">
                                <div class="control-group span5">
                                  <label class="control-label" for="inputIcon">Minimo:</label>
                                  <div class="controls">
                                    <div class="input-prepend">
                                      <span class="add-on"><i class="icon-envelope"></i></span>
                                      <input class="span5" id="inputIcon" type="text">
                                    </div>
                                  </div>
                                </div>
                                <div class="control-group span5">
                                  <label class="control-label" for="inputIcon">Maximo:</label>
                                  <div class="controls">
                                    <div class="input-prepend">
                                      <span class="add-on"><i class="icon-envelope"></i></span>
                                      <input class="span5" id="inputIcon" type="text">
                                    </div>
                                  </div>
                                </div>
                            </div>
                        </div>
                        <div class="row-fluid crear-evento-3 event">
                            <h2>Elige el lugar del evento</h2>
                            <div class="span12 event-padding dev-padd">
                                <div id="map" style="border:1px solid #eee;"></div>
                            </div>
                            <div class="span3 lugar-nm event-padding">
                                <div class="form-item">
                                    <div id="cityId-label" class="item-label">
                                        <label for="cityId" class="required">Ciudad</label>
                                    </div>
                                    <div class="item-value">
                                        <select name="cityId" id="cityId" class="input-block-level">
                                            <option value="PER-LIM" label="Lima, Perú" selected="selected">Lima, Perú</option>
                                        </select>
                                    </div>
                                </div>       
                            </div>
                            <div class="span5">
                                <div class="form-item tooltip-errors">
                                    <div id="address-label" class="item-label">
                                        <label for="address" class="required">Dirección</label>
                                    </div>
                                    <div class="item-value">
                                        <input type="text" name="address" id="address" value="" maxlength="150" class="input-block-level">
                                    </div>
                                </div>      
                            </div>
                            <div class="span3">
                                <div class="form-item tooltip-errors">
                                    <div id="addressReference-label" class="item-label">
                                        <label for="addressReference" class="optional">Referencia de ubicación</label>
                                    </div>
                                    <div class="item-value">
                                        <input type="text" name="addressReference" id="addressReference" value="" maxlength="250" class="input-block-level">
                                    </div>
                                </div>            
                                <input type="hidden" name="mapLocationLat" value="" id="mapLocationLat">            
                                <input type="hidden" name="mapLocationLon" value="" id="mapLocationLon">        
                            </div>
                        </div>
                        <div class="row-fluid crear-evento-4 event">
                            <h2>Notificaciones</h2>
                            <div class="span10 noti-span span-dev">
                                <label class="checkbox">
                                    <input type="checkbox"> Cuando alguien se une a la actividad
                                </label>
                                <label class="checkbox">
                                    <input type="checkbox"> Cuando alguien abandona el grupo
                                </label>
                                <label class="checkbox">
                                    <input type="checkbox"> Notificacion cuando el organizador crea un grupo
                                </label>
                            </div>
                        </div>
                        <p class="crear-evento">
                            <input type="submit" class="btn btn-info btn-large" value="Crear evento" />
                        </p>
                    </form>
                </div>
            </div>
        </div> <!-- #main-container -->



<!--
<?php
$title = 'Agregar nuevo grupo';
$this->headTitle($title);
?>

<div class="span12">
<?php
//$form = $this->form;
//
//$form->setAttributes(array(
//    'action' => $this->url.'/grupo/index/agregargrupo',
//    'method' => 'post',
//    'class'=>'form-horizontal'
//));
//
//$form->prepare();
//echo $this->form()->openTag($form);
?>
<legend><?php echo $this->escapeHtml($title); ?></legend>
<?php // echo $this->formHidden($form->get('in_id'));?>

<div class="row-fluid">
<div class="control-group span6"><?php // echo $this->formRow($form->get('va_nombre'));?></div>
<div class="control-group span6"><?php // echo $this->formRow($form->get('va_imagen'));?></div>
</div>
<div class="row-fluid">
<div class="control-group span5"><?php // echo $this->formRow($form->get('va_descripcion'));?></div>

<div class="control-group span3"><?php // echo $this->formRow($form->get('ta_ubigeo_in_id'));?></div>
<div class="control-group span3"><?php // echo $this->formRow($form->get('ta_categoria_in_id'));?></div>
 
<div class="control-group span3"><?php // echo $this->formRow($form->get('tipo_notificacion'));?></div>
</div>
<div class="row-fluid">
<div class="control-group span12 "><?php // echo $this->formSubmit($form->get('submit'));?></div></div><?php // echo $this->form()->closeTag();?> 
</div>-->
