		<div class="main-container">
            <div class="container">
                <!--Crear Grupo-->
                <div class="row-fluid elige-crea">
                    <div class="crear-grupo-agregar">
                        <div class="row-fluid">
                            <div class="span12 crear-evento event">
                                <h1>Elige tu grupo o crea un nuevo grupo</h1>
                                <p>¡Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy!</p>
                            </div>
                        </div>
                        <div class="row-fluid event nmb">
                            <div class="span12 space-group">
                                <label>Elige tu grupo:</label>
                                 <select name="grupos" class="span11 nm-crear-grupo" id="crearGrupo">
                                    <option value="" label="..Elige un grupo..">..Elige un grupo..</option>
                                <?php foreach($this->grupos as $grupo): ?>
                                    <option value="<?php echo $grupo['ta_grupo_in_id'];?>" label="<?php echo $grupo['nom_grup'];?>"><?php echo $grupo['nom_grup'];?></option>
                                <?php endforeach; ?>
                               </select>
                            </div>
                            <p class="activar-agregar" style="margin-top:10px;margin-left:10px;">
                                <a href="#" class="btn btn-primary btn-agregar">Agregar un nuevo grupo</a>
                            </p>
                        </div>
                    </div><!--Crear grupo o agregar-->
                    <p class="next-space" style="display:none;">
                        <a href="#" class="btn btn-warning next-grupo">Siguiente</a>
                    </p>
                </div>    
                <div class="row-fluid crear-grupos" style="display:none;">
                    <?php
                    $form = $this->form;

                    $form->setAttributes(array(
                        'action' => $this->url.'/grupo/index/agregargrupo',
                        'method' => 'post',
                        'class'=>'span12 form-crear-grupo',
                        'id'=>'crear-group'
                    ));

                    $form->prepare();
                    echo $this->form()->openTag($form);
                    ?>
                    <!--<form action="" class="span12 form-crear-grupo" id="crear-group">-->
                        <div class="row-fluid">
                            <div class="span12 crear-evento event">
                                <h1>Crear tu grupo</h1>
                                <p>¡Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy!</p>
                            </div>
                        </div>
                        <div class="row-fluid event nmb">
                            <div class="span8 space-group">
                                <?php echo $this->formHidden($form->get('in_id'));?>
                                <?php echo $this->formRow($form->get('va_nombre'));?>
                                <?php echo $this->formRow($form->get('ta_categoria_in_id'));?>
                                <?php echo $this->formRow($form->get('va_descripcion'));?>
                            </div>
                            <div class="span4 space-group">
                                <div class="control-group">
                                    <label for="textfield" class="control-label"></label>
                                    <div class="controls">
                                        <div class="fileupload fileupload-new" data-provides="fileupload">
                                            <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
                                                <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" />
                                            </div>
                                            <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                                            <div>
                                                <span class="btn btn-file">
                                                    <span class="fileupload-new">Select image</span>
                                                    <span class="fileupload-exists">Change</span>
                                                   <?php echo $this->formRow($form->get('va_imagen'));?>
                                                </span>
                                                <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <p class="crear-evento">
                            <?php echo $this->formSubmit($form->get('submit'));?>
                            <a href="#" class="btn btn-inverse btn-cancelar">Cancelar</a>
                        </p>
                    <!--</form>-->
                    <?php echo $this->form()->closeTag();?>
                </div>        
                <!--Agregar eventos-->
            </div>
        </div> <!-- #main-container -->

<!--
<?php
$title = 'Agregar nuevo grupo';
$this->headTitle($title);
?>

<div class="span12">
<?php
//$form = $this->form;
//
//$form->setAttributes(array(
//    'action' => $this->url.'/grupo/index/agregargrupo',
//    'method' => 'post',
//    'class'=>'form-horizontal'
//));
//
//$form->prepare();
//echo $this->form()->openTag($form);
?>
<legend><?php echo $this->escapeHtml($title); ?></legend>
<?php // echo $this->formHidden($form->get('in_id'));?>

<div class="row-fluid">
<div class="control-group span6"><?php // echo $this->formRow($form->get('va_nombre'));?></div>
<div class="control-group span6"><?php // echo $this->formRow($form->get('va_imagen'));?></div>
</div>
<div class="row-fluid">
<div class="control-group span5"><?php // echo $this->formRow($form->get('va_descripcion'));?></div>

<div class="control-group span3"><?php // echo $this->formRow($form->get('ta_ubigeo_in_id'));?></div>
<div class="control-group span3"><?php // echo $this->formRow($form->get('ta_categoria_in_id'));?></div>
 
<div class="control-group span3"><?php // echo $this->formRow($form->get('tipo_notificacion'));?></div>
</div>
<div class="row-fluid">
<div class="control-group span12 "><?php // echo $this->formSubmit($form->get('submit'));?></div></div><?php // echo $this->form()->closeTag();?> 
</div>-->
