<div class="main-container">
	<div class="container">
		<div class="row-fluid">
		  	<div class="span3 group-sidebar">
                <div class="img-grupo">
                    <img src="<?php   echo $this->host('images') . '/grupos/general/' . htmlspecialchars($this->grupo[0]['va_imagen'], ENT_QUOTES, 'utf-8');  ?>">
                </div>
                <h2 class="gh"><a href="#"><?php echo $this->grupo[0]['va_nombre']; ?></a></h2>
                <p class="fund gh"><em>Fundado el <?php  $fecha = date_create($this->grupo[0]['va_fecha']);
                                         echo $fecha = date_format($fecha, "d \d\e\l m \d\e\l Y"); ?></em></p>
                <p class="desc gh">
                 <?php echo $this->grupo[0]['va_descripcion']; ?> Juntar figurita de Pikachu&nbsp; <br> <a href="#">Ver mas...</a>
                </p>
                <p class="gh ft"><a class="dp" href="#"><span class="cant-user ab">Nº Usuarios</span> <span class="nm"><?php echo $this->grupo[0]['cantidad']; ?></span></a></p>
                <p class="gh ft"><a class="dp" href="#"><span class="cant-evento-f ab">Evento futuros</span> <span class="nm"><?php echo $this->eventosfuturos[0]['eventosfuturos']; ?></span></a></p>
                <p class="gh ft"><a class="dp" href="#"><span class="cant-evento-p ab">Evento pasados</span> <span class="nm"><?php echo $this->eventospasados[0]['eventospasados']; ?></span></a></p>
		  	</div>
		  <div class="span6 group-sidebar list-event">
		    <h4>Eventos recientes</h4>
		    <ul class="lista-evento">
                        <?php  foreach ($this->proximos_eventos  as $proximos_eventos) :?>
		        <li>
		          	<div class="det-even">
						<div class="row-fluid">
							<div class="span12 cont-eve">
								<p class="pp"> <?php  $fecha = date_create($this->escapeHtml($proximos_eventos->va_fecha));
                                         echo $fecha = date_format($fecha, "d \d\e\l m \d\e\l Y  h:m:s"); ?></p>
							</div>
						</div>
						<div class="row-fluid">
							<div class="span4">
								<a href="/evento/<?php echo $this->escapeHtml($proximos_eventos->in_id);?>"><img src="<?php   echo $this->host('images') . '/eventos/principal/' . $this->escapeHtml($proximos_eventos->va_imagen)  ?>" alt=""></a>
							</div>
							<div class="span8">
								<div class="cont-eve">
                                   <?php $fecha_actual = date("Y-m-d h:m:s"); 
                                   if ( $this->escapeHtml($proximos_eventos->va_fecha) >= $fecha_actual)
                                     {}
                                   else{?> <h2>EVENTO CADUCADO</h2> <?php } ?>          
					              	<h3><a href="/evento/<?php echo $this->escapeHtml($proximos_eventos->in_id); ?>"><?php echo  $this->escapeHtml($proximos_eventos->va_nombre);?></a></h3>
					              	<p><?php echo  $this->escapeHtml($proximos_eventos->va_descripcion);?></p>
					            </div>		
							</div>
						</div>
						<div class="row-fluid">
							<div class="span12 mienbros-evento">
								<p><?php echo  $this->escapeHtml($proximos_eventos->miembros);?> Miembros.</p>
							</div>
						</div>
		          	</div>
		        </li> 
                        <?php endforeach;  ?>
		    </ul>
                    <div class="row-fluid">
            <div class="span12" id="pagina">
                <?php echo (count($this->proximos_eventos)> 0)?$this->paginationControl($this->proximos_eventos, 'Sliding', 'grupo/evento/paginador.phtml',array('variable'=>'/grupo/index/detallegrupo/'.$this->in_id.'?')):""; ?>
            </div>
                    </div>
	 </div>
		  <div class="span3 group-sidebar">
		  	<div class="row-fluid">
		  		<div class="span12 unete-grupo">
		  			<p>
		  			  <?php if($session){?>
                          <?php if($participa){?>
                          <a href="#" class="btn btn-danger" id="uneteAbEvent">Abandona el Grupo</a> 
                          <?php }else{?>
                          <a href="#" class="btn btn-success" id="uneteEvent">Unete al Grupo</a> 
                          <?php }?>
                        <?php }else{?>
                          <a href="#inline_evento" class="btn btn-success inlineEvento">Unete al Grupo</a> 
                       <?php }?>          
                          
<!-- 		  				<a href="#" id="unete-grupo" class="btn btn-danger"><i class="icon-foto"></i> Unete al Grupo</a> -->
						<!--<a href="#" class="btn btn-danger"><i class="icon-foto"></i> Abandonar el Grupo</a> -->
		  			</p>
		  		</div>
		  	</div>
		 <div class="lista-usuario">
                  <ul>
                    <li>
                      <div class="users">
                         <?php  foreach ($this->usuarios  as $usuarios) :?>
                        <div class="row-fluid">
                            <div class="span4 img-user-ev">
                            	<img src="/img/foto-carnet.jpg">
                               <!--<img src="<?php   echo $this->host('images') . '/usuario/principal/' . htmlspecialchars($usuarios->imagen, ENT_QUOTES, 'utf-8');  ?>" alt="">-->
                            </div>
                            <div class="span8 desc-user">
                                <h3><a href="#"><?php echo  $this->escapeHtml($usuarios->nombre_usuario);?></a></h3>
                               <p><?php echo  $this->escapeHtml($usuarios->descripcion_usuario);?></p>
                            </div>
                        </div>
                        <div class="row-fluid unio">
                           <p class="span12">Se unio el <?php  $fecha = date_create($this->escapeHtml($usuarios->va_fecha));
                                         echo $fecha = date_format($fecha, "d \d\e\l m \d\e\l Y"); ?></p>
                        </div>
                          <?php endforeach;  ?>
                      </div>
                    </li>
                  </ul>
               </div>
		    <!--  <div class="afiliarse">
		        <p>
		        <a href=""><i class="icon-user-add"></i>Afiliarse al Grupo</a>
		        </p>
		    </div> -->
		  </div>
		</div>
	</div>
</div>

<script type="text/javascript">
	
	$(document).on('ready', function(){		
		enviarDatos();
    	abandonarDatos();
	});

	function enviarDatos(){
    var even = <?php echo $this->idevento; ?>;
    $("#uneteEvent").on('click', function(e){
      e.preventDefault();
      $(".btn-unete").empty();
      var addLoading = '<img src="/img/cargando.gif" />';
      $(".btn-unete").html(addLoading);
      var activo = 1;
      $.ajax({
        url: '/grupo/evento/unir',
        type: 'get',
        data: 'act=' + activo +'&idE='+even,
        dataType: "json",
        success: function(data){
          var agregarButton = '<a href="#" class="btn btn-danger" id="uneteAbEvent">Abandona el evento</a>';
          $(".btn-unete").empty();
          $(".btn-unete").html(agregarButton);
        },
        error: function(){
            console.log('Fallo conectando con el servidor')
        }
      });
    });
  }

  function abandonarDatos(){
    var even = <?php echo $this->idevento; ?>;
    $("#uneteAbEvent").on('click', function(e){
      e.preventDefault();
      $(".btn-unete").empty();
      var addLoading = '<img src="/img/cargando.gif" />';
      $(".btn-unete").html(addLoading);
      var activo = 0;
      $.ajax({
        url: '/grupo/evento/unir',
        type: 'get',
        data: 'act=' + activo +'&idE='+even,
        dataType: "json",
        success: function(data){
          var agregarButton = '<a href="#" class="btn btn-success" id="uneteEvent">Unete al evento</a>';
          $(".btn-unete").empty();
          $(".btn-unete").html(agregarButton);
        },
        error: function(){
            console.log('Fallo conectando con el servidor')
        }
      });
    });
  }

</script>