<div class="main-container">
    <div class="container">
        <?php if ($this->mensajes) { ?>
            <div class="row-fluid">
                <div class="alert alert-success alert-margin">
                    <?php
                    foreach ($this->mensajes as $message) {
                        echo $message;
                    }
                    ?>
                </div>
            </div>
        <?php } ?>
        <div class="row-fluid">
            <div class="span3 group-sidebar">
                <div class="img-grupo">
                    <img src="<?php echo $this->host('images') . '/grupos/general/' . htmlspecialchars($this->grupo[0]['va_imagen'], ENT_QUOTES, 'utf-8'); ?>">
                </div>
                <?php if($this->grupo[0]['ta_usuario_in_id']==$session->in_id){?>
                <div class="editarGrupo">
                    <a href="/grupo/editar/<?php echo $this->in_id ?>" class="btn btn-success">Editar</a>
                </div>
                <?php }?>
                <h2 class="gh"><a href="#"><?php echo $this->grupo[0]['va_nombre']; ?></a></h2>
                <p class="fund gh"><em>Fundado el <?php
                $fecha = date_create($this->grupo[0]['va_fecha']);
                $arrayMeses = array('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                    'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
                echo date_format($fecha, "d") . ' de ' . $arrayMeses[date('m') - 1] . ' del ' . date_format($fecha, "Y");
                ?></em></p>
                <p class="desc gh">
                <?php echo $this->grupo[0]['va_descripcion']; ?><br> 
                </p>
                <p class="gh ft"><span class="cant-user ab">Nº Usuarios</span> <span class="nm"><?php echo $this->grupo[0]['cantidad']; ?></span></p>
                <p class="gh ft"><span class="cant-evento-f ab">Evento futuros</span> <span class="nm"><?php echo $this->eventosfuturos[0]['eventosfuturos']; ?></span></p>
                <p class="gh ft"><span class="cant-evento-p ab">Evento pasados</span> <span class="nm"><?php echo $this->eventospasados[0]['eventospasados']; ?></span></p>
            </div>
            <div class="span6 group-sidebar list-event">
                <h4>Eventos recientes</h4>
                <ul class="lista-evento">
                    <?php foreach ($this->proximos_eventos as $proximos_eventos) : ?>
                        <li>
                            <div class="det-even">
                                <div class="row-fluid">
                                    <div class="span12 cont-eve">
                                        <p class="pp"> <?php
                                            $fecha = date_create($this->escapeHtml($proximos_eventos->va_fecha));
                                            $arrayMeses = array('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                                                'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
                                            echo date_format($fecha, "d") . ' de ' . $arrayMeses[date('m') - 1] . ' del ' . date_format($fecha, "Y") . ' ' . date_format($fecha, "h:m:s");
                                            ?>                                
                                        </p>
                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <div class="span4 dnv-img">
                                        <a href="/evento/<?php echo $this->escapeHtml($proximos_eventos->in_id); ?>"><img src="<?php echo $this->host('images') . '/eventos/principal/' . $this->escapeHtml($proximos_eventos->va_imagen) ?>" alt=""></a>
                                    </div>
                                    <div class="span8 dvn-decs">
                                        <div class="cont-eve">
                                        <?php
                                        $fecha_actual = date("Y-m-d h:m:s");
                                        if ($this->escapeHtml($proximos_eventos->va_fecha) >= $fecha_actual) {
                                            
                                        } else {
                                            ?> <h2>EVENTO CADUCADO</h2> <?php } ?>          
                                            <h3><a href="/evento/<?php echo $this->escapeHtml($proximos_eventos->in_id); ?>"><?php echo $this->escapeHtml($proximos_eventos->va_nombre); ?></a></h3>
                                            <?php 
                                            $descrip=strip_tags(html_entity_decode($proximos_eventos->va_descripcion));
                                            if(strlen($descrip)>250){
                                                $strdescrip=trim(substr($descrip, 0, 247));
                                                 $strdescrip.='...';
                                                }else {$strdescrip=$descrip;} ?>
                                            <p><?php echo $strdescrip; ?></p>
                                        </div>		
                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <div class="span12 mienbros-evento">
                                        <p><?php echo $this->escapeHtml($proximos_eventos->miembros); ?> Miembros.</p>
                                    </div>
                                </div>
                            </div>
                        </li> 
<?php endforeach; ?>
                </ul>
                <div class="row-fluid">
                    <div class="span12" id="pagina">
                        <?php echo (count($this->proximos_eventos) > 0) ? $this->paginationControl($this->proximos_eventos, 'Sliding', 'grupo/evento/paginador.phtml', array('variable' => '/grupo/index/detallegrupo/' . $this->in_id . '?')) : ""; ?>
                    </div>
                </div>
            </div>
            <div class="span3 group-sidebar">
                <div class="row-fluid">
                    <div class="span12">         
                        <div class="span12 unete-grupo"> 
                            <?php 
                          if($this->grupo[0]['ta_usuario_in_id']!=$session->in_id){
                            if ($session) { ?>
                                <?php if ($participa=='activo') { ?>
                                    <a href="#" class="btn btn-danger uneteAbEvent" id="uneteAbEvent">Abandona el Grupo</a> 
                                    <a href="#" class="btn btn-success uneteEvent" id="uneteEvent" style="display:none;">Haz una reservación</a> 
                                <?php } elseif($participa=='desactivo'){ ?>
                                    <a href="#" class="btn btn-success uneteEvent" id="uneteEvent">Haz una reservación</a>
    
                            <?php }elseif($participa=='pendiente'){ ?>
                                    <a href="#" class="btn btn-success disabled" id="uneteEvent" disabled="disabled">Pendiente</a>
                                    <?php }else{?>
                                    <a href="#" class="btn btn-success uneteEvent" id="uneteEvent">Haz una reservación</a>
                                     <?php }?>
                            <?php } else { ?>
                                <a href="#inline_evento" class="btn btn-success inlineEvento">Haz una reservación</a> 
                                    <?php } ?> 
                                
                            <?php } ?>
                        </div>
                    </div>      
                </div>
       <?php if($this->grupo[0]['ta_usuario_in_id']==$session->in_id){?>
                <?php if(!empty($this->usuariospendiente)){ ?>
                <div class="row-fluid user-espera user-list-group">
                    <div class="span12 user-back-1">
                        <h3>Usuarios en espera</h3>
                        <ul>
                            <?php foreach($this->usuariospendiente as $usuariopendiente){ ?>
                            <li id="user-<?php echo $usuariopendiente->ta_usuario_in_id;?>">
                                <input class="marcar-user" type="checkbox"  data-user="<?php echo $usuariopendiente->ta_usuario_in_id;?>"> 
                                <label class="checkbox img-cargar-usuarios">
                                    <img src="<?php echo $this->host('images').'/usuario/detalle/'.$usuariopendiente->imagen;?>" title="<?php echo $usuariopendiente->nombre_usuario;?>">
                                    <a href="#"><?php echo $usuariopendiente->nombre_usuario;?></a>
                                    <p>
                                        <?php echo $usuariopendiente->descripcion_usuario;?>
                                    </p>
                                </label>
                            </li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
               <?php } ?>
                <?php if(!empty($this->usuariosaceptado)){ ?>
                <div class="row-fluid user-aprobado user-list-group">
                    <div class="span12 user-back-2">
                        <h3>Usuarios aprobados</h3>
                        <ul>
                            <?php foreach($this->usuariosaceptado as $usuarioaceptado){ ?>
                            <?php if($usuarioaceptado->ta_usuario_in_id != $this->grupo[0]['ta_usuario_in_id']){?>
                            <li id="user-<?php echo $usuarioaceptado->ta_usuario_in_id;?>">
                                <input class="marcar-user" type="checkbox" data-user="<?php echo $usuarioaceptado->ta_usuario_in_id;?>"> 
                                <label class="checkbox img-cargar-usuarios">
                                    <img src="<?php echo $this->host('images').'/usuario/detalle/'.$usuarioaceptado->imagen;?>" title="<?php echo $usuarioaceptado->nombre_usuario;?>">
                                    <a href="#"><?php echo $usuarioaceptado->nombre_usuario;?></a>
                                    <p>
                                        <?php echo $usuarioaceptado->descripcion_usuario;?>
                                    </p>
                                </label>
                            </li>
                            <?php } ?>
                             <?php } ?>
                        </ul>
                    </div>
                </div>
                <?php } ?>
        <?php }else{?>
                <?php if($this->usuarios ){?>
                <div class="lista-usuario">
                    <ul>
                        <?php foreach ($this->usuarios as $usuarios) : ?>
                        <li id="user-<?php echo $usuarios->ta_usuario_in_id;?>">
                            <div class="users">
                                <div class="row-fluid">
                                    <div class="span4 img-user-ev">
                                    <?php $valor = explode('/',$usuarios->imagen);
                                    if($valor[0]=='https:'){ ?>  
                                        <img src="<?php echo $usuarios->imagen ;?>">                                            
                                    <?php } else {
                                        if(($usuarios->imagen)!="foto-carnet.jpg"){?>
                                            <img src="<?php echo $this->host('images') ?>/usuario/detalle/<?php echo $usuarios->imagen ;?>" >
                                        <?php }else{?>
                                            <img src="<?php echo $this->host('img') ?>/foto-carnet.jpg">
                                        <?php } 
                                    }?>  
                                    </div>
                                    <div class="span8 desc-user">
                                        <h3><?php echo $this->escapeHtml($usuarios->nombre_usuario); ?></h3>
                                        <p><?php echo $this->escapeHtml($usuarios->descripcion_usuario); ?></p>
                                    </div>
                                </div>
                                <div class="row-fluid unio">
                                    <p class="span12">Se unió el <?php
                                    $fecha = date_create($this->escapeHtml($usuarios->va_fecha));
                                    $arrayMeses = array('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                                        'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
                                    echo date_format($fecha, "d") . ' de ' . $arrayMeses[date('m') - 1] . ' del ' . date_format($fecha, "Y");
                                    ?></p>
                                </div>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                 <?php }?>
                
         <?php }?>
                <!--  <div class="afiliarse">
                    <p>
                    <a href=""><i class="icon-user-add"></i>Afiliarse al Grupo</a>
                    </p>
                </div> -->
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
	var hostUrl = '<?php echo $this->host("images")?>/usuario/detalle/';
    $(document).on('ready', function(){		

        usuarioEspera();
        usuarioAprobados();
        enviarDatos();
        abandonarDatos();
    });

    function usuarioEspera(){
        var even = <?php echo $this->in_id; ?>;
        $('.user-espera input').click(function(e){
            e.preventDefault();
            var agregarLoading = '<div class="loading-usuario"><div class="img-loading-dep"><img src="/img/loading.gif"></div></div>';
            $(".user-back-1").append(agregarLoading);
            var dataUser = $(this).attr('data-user');
            var activo = 2;
            $.ajax({
                url: '/grupo/index/aprobar',
                type: 'get',
                data: 'id_grupo='+even+'&id_usuario='+dataUser +'&act='+activo,
                dataType: "json",
                success: function(data){
                    $(".user-back-1 .loading-usuario").remove();
                    $(".user-back-1 ul li#user-"+dataUser).remove();
                    var dataUsuario = '<li id="user-'+data.userestado["id"]+'">'+
                                '<input class="marcar-user" type="checkbox" data-user="'+data.userestado["id"]+'">'+
                                '<label class="checkbox img-cargar-usuarios">'+
                                    '<img src="'+hostUrl+data.userestado["imagen"]+'" title="">'+
                                    '<a href="#">'+data.userestado["nombre_usuario"]+'</a>'+
                                    '<p>'+data.userestado["descripcion_usuario"]+'</p>'+
                                '</label>'+
                            '</li>';
                    $(".user-back-2 ul").prepend(dataUsuario);
                },
                error: function(){
                    console.log('Fallo conectando con el servidor')
                }
            });
        });
    }

    function usuarioAprobados(){
        var even = <?php echo $this->in_id; ?>;
        $('.user-aprobado input').click(function(e){
            e.preventDefault();
            var agregarLoading = '<div class="loading-usuario"><div class="img-loading-dep"><img src="/img/loading.gif"></div></div>';
            $(".user-back-2").append(agregarLoading);
            var dataUser = $(this).attr('data-user');
            var activo = 1;
            $.ajax({
                url: '/grupo/index/aprobar',
                type: 'get',
                data: 'id_grupo='+even+'&id_usuario='+dataUser +'&act='+activo,
                dataType: "json",
                success: function(data){
                    $(".user-back-2 .loading-usuario").remove();
                    $(".user-back-2 ul li#user-"+dataUser).remove();
                },
                error: function(){
                    console.log('Fallo conectando con el servidor')
                }
            });
        });
    }

    function enviarDatos(){
        var even = <?php echo $this->in_id; ?>;
        $(".uneteEvent").on('click', function(e){
            e.preventDefault();
            var addLoading = '<img class="img-lo" src="/img/cargando.gif" />';
            $(".unete-grupo").append(addLoading);
            $(".uneteAbEvent").hide();
            var activo = 1;
            $.ajax({
                url: '/grupo/index/unir',
                type: 'get',
                data: 'act=' + activo +'&idE='+even,
                dataType: "json",
                success: function(data){
                    $(".img-lo").hide();                    
                    var dataPer = '<li id="user-'+data.userestado["id"]+'">'+
                                    '<div class="users">'+
                                        '<div class="row-fluid">'+
                                            '<div class="span4 img-user-ev">'+
                                                '<img src="'+hostUrl+data.userestado["imagen"]+'" alt="">'+
                                            '</div>'+
                                            '<div class="span8 desc-user">'+
                                                '<h3>'+data.userestado["nombre_usuario"]+'</h3>'+
                                                '<p>'+data.userestado["descripcion_usuario"]+'</p>'+
                                            '</div>'+
                                        '</div>'+
                                        '<div class="row-fluid unio">'+
                                            '<p class="span12">'+data.userestado["va_fecha"]+'</p>'+
                                        '</div>'+
                                    '</div>'+
                                    '</li>';
                    $(".lista-usuario ul").prepend(dataPer);
                    $(".uneteEvent").addClass("disabled");
                    $(".uneteEvent").attr("disabled", "disabled");
                    $("a.uneteEvent").text("Pendiente");
                    $("#uneteEvent").removeClass("uneteEvent");
                },
                error: function(){
                    console.log('Fallo conectando con el servidor')
                }
            });
        });
        
        $("#uneteEvent").click(function(e){
            e.preventDefault();
        });
    }

    function abandonarDatos(){
        var even = <?php echo $this->in_id; ?>;
        $(".uneteAbEvent").on('click', function(e){
            e.preventDefault();
            var addLoading = '<img class="img-lo" src="/img/cargando.gif" />';
            $(".unete-grupo").append(addLoading);
            $(".uneteAbEvent").hide();
            $(".uneteEvent").hide();
            var activo = 0;
            $.ajax({
                url: '/grupo/index/unir',
                type: 'get',
                data: 'act=' + activo +'&idE='+even,
                dataType: "json",
                success: function(data){
                    var datoId = data.userestado["id"]; 
                    $(".img-lo").hide();
                    $(".uneteEvent").show();
                    $(".lista-usuario ul li#user-"+datoId).remove();
                },
                error: function(){
                    console.log('Fallo conectando con el servidor')
                }
            });
        });
    }


</script>