<div class="main-container">
    <div class="container">
        <?php if ($this->mensajes) { ?>
            <div class="row-fluid">
                <div class="alert alert-success alert-margin">
                    <?php
                    foreach ($this->mensajes as $message) {
                        echo $message;
                    }
                    ?>
                </div>
            </div>
        <?php } ?>
        <div class="row-fluid">
            <div class="span3 group-sidebar">
                <div class="img-grupo">
                    <img src="<?php echo $this->host('images') . '/grupos/general/' . htmlspecialchars($this->grupo[0]['va_imagen'], ENT_QUOTES, 'utf-8'); ?>">
                </div>
                <?php if($this->grupo[0]['ta_usuario_in_id']==$session->in_id){?>
                <div class="editarGrupo">
                    <a href="/grupo/editar/<?php echo $this->in_id ?>" class="btn btn-success">Editar</a>
                </div>
                <?php }?>
                <h2 class="gh"><a href="#"><?php echo $this->grupo[0]['va_nombre']; ?></a></h2>
                <p class="fund gh"><em>Fundado el <?php
                $fecha = date_create($this->grupo[0]['va_fecha']);
                $arrayMeses = array('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                    'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
                echo date_format($fecha, "d") . ' de ' . $arrayMeses[date('m') - 1] . ' del ' . date_format($fecha, "Y");
                ?></em></p>
                <p class="desc gh">
                <?php echo $this->grupo[0]['va_descripcion']; ?><br> 
                </p>
                <p class="gh ft"><a class="dp" href="#"><span class="cant-user ab">Nº Usuarios</span> <span class="nm"><?php echo $this->grupo[0]['cantidad']; ?></span></a></p>
                <p class="gh ft"><a class="dp" href="#"><span class="cant-evento-f ab">Evento futuros</span> <span class="nm"><?php echo $this->eventosfuturos[0]['eventosfuturos']; ?></span></a></p>
                <p class="gh ft"><a class="dp" href="#"><span class="cant-evento-p ab">Evento pasados</span> <span class="nm"><?php echo $this->eventospasados[0]['eventospasados']; ?></span></a></p>
            </div>
            <div class="span6 group-sidebar list-event">
                <h4>Eventos recientes</h4>
                <ul class="lista-evento">
                    <?php foreach ($this->proximos_eventos as $proximos_eventos) : ?>
                        <li>
                            <div class="det-even">
                                <div class="row-fluid">
                                    <div class="span12 cont-eve">
                                        <p class="pp"> <?php
                                            $fecha = date_create($this->escapeHtml($proximos_eventos->va_fecha));
                                            $arrayMeses = array('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                                                'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
                                            echo date_format($fecha, "d") . ' de ' . $arrayMeses[date('m') - 1] . ' del ' . date_format($fecha, "Y") . ' ' . date_format($fecha, "h:m:s");
                                            ?>                                
                                        </p>
                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <div class="span4 dnv-img">
                                        <a href="/evento/<?php echo $this->escapeHtml($proximos_eventos->in_id); ?>"><img src="<?php echo $this->host('images') . '/eventos/principal/' . $this->escapeHtml($proximos_eventos->va_imagen) ?>" alt=""></a>
                                    </div>
                                    <div class="span8 dvn-decs">
                                        <div class="cont-eve">
                                        <?php
                                        $fecha_actual = date("Y-m-d h:m:s");
                                        if ($this->escapeHtml($proximos_eventos->va_fecha) >= $fecha_actual) {
                                            
                                        } else {
                                            ?> <h2>EVENTO CADUCADO</h2> <?php } ?>          
                                            <h3><a href="/evento/<?php echo $this->escapeHtml($proximos_eventos->in_id); ?>"><?php echo $this->escapeHtml($proximos_eventos->va_nombre); ?></a></h3>
                                            <?php 
                                            $descrip=strip_tags(html_entity_decode($proximos_eventos->va_descripcion));
                                            if(strlen($descrip)>250){
                                                $strdescrip=trim(substr($descrip, 0, 247));
                                                 $strdescrip.='...';
                                                }else {$strdescrip=$descrip;} ?>
                                            <p><?php echo $strdescrip; ?></p>
                                        </div>		
                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <div class="span12 mienbros-evento">
                                        <p><?php echo $this->escapeHtml($proximos_eventos->miembros); ?> Miembros.</p>
                                    </div>
                                </div>
                            </div>
                        </li> 
<?php endforeach; ?>
                </ul>
                <div class="row-fluid">
                    <div class="span12" id="pagina">
                        <?php echo (count($this->proximos_eventos) > 0) ? $this->paginationControl($this->proximos_eventos, 'Sliding', 'grupo/evento/paginador.phtml', array('variable' => '/grupo/index/detallegrupo/' . $this->in_id . '?')) : ""; ?>
                    </div>
                </div>
            </div>
            <div class="span3 group-sidebar">
                <div class="row-fluid">
            
                            <div class="span12">
                                
                    <div class="span12 unete-grupo"> 
                        <?php 
                      if($this->grupo[0]['ta_usuario_in_id']!=$session->in_id){
                        if ($session) { ?>
                            <?php if ($participa) { ?>
                                <a href="#" class="btn btn-danger uneteAbEvent" id="uneteAbEvent">Abandona el Grupo</a> 
                                <a href="#" class="btn btn-success uneteEvent" id="uneteEvent" style="display:none;">Unete al Grupo</a> 
                            <?php } else { ?>
                                <a href="#" class="btn btn-success uneteEvent" id="uneteEvent">Unete al Grupo</a>
                                <a href="#" class="btn btn-danger uneteAbEvent" id="uneteAbEvent" style="display:none;">Abandona el Grupo</a> 
                        <?php } ?>
                    <?php } else { ?>
                            <a href="#inline_evento" class="btn btn-success inlineEvento">Unete al Grupo</a> 
                                <?php } ?> 
                            
                            <?php }else{?>
                            <?php }?>
                    </div>
                </div>
                    
  </div>
                
                <div class="lista-usuario">
                    <ul>

                                        <?php foreach ($this->usuarios as $usuarios) : ?>
                       <li id="user-<?php echo $usuarios->ta_usuario_in_id;?>">
                            <div class="users">
                                    <div class="row-fluid">
                                        <div class="span4 img-user-ev">
    <?php if (($usuarios->imagen) != "foto-carnet.jpg") { ?>
                                                <img src="<?php echo $this->host('images') ?>/usuario/detalle/<?php echo $usuarios->imagen; ?>" alt="">
    <?php } else { ?>
                                                <img src="<?php echo $this->host('img') ?>/foto-carnet.jpg" alt="">
    <?php } ?>
                                        </div>
                                        <div class="span8 desc-user">
                                            <h3><a href="#"><?php echo $this->escapeHtml($usuarios->nombre_usuario); ?></a></h3>
                                            <p><?php echo $this->escapeHtml($usuarios->descripcion_usuario); ?></p>
                                        </div>
                                    </div>
                                    <div class="row-fluid unio">
                                        <p class="span12">Se unió el <?php
                                        $fecha = date_create($this->escapeHtml($usuarios->va_fecha));
                                        $arrayMeses = array('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                                            'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
                                        echo date_format($fecha, "d") . ' de ' . $arrayMeses[date('m') - 1] . ' del ' . date_format($fecha, "Y");
                                        ?></p>
                                    </div>
                               </div>
                        </li>
<?php endforeach; ?>

                    </ul>
                </div>
                <!--  <div class="afiliarse">
                    <p>
                    <a href=""><i class="icon-user-add"></i>Afiliarse al Grupo</a>
                    </p>
                </div> -->
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
	
    $(document).on('ready', function(){		
        enviarDatos();
        abandonarDatos();
    });

    function enviarDatos(){
        var even = <?php echo $this->in_id; ?>;
        $(".uneteEvent").on('click', function(e){
            e.preventDefault();
            var addLoading = '<img class="img-lo" src="/img/cargando.gif" />';
            $(".unete-grupo").append(addLoading);
            $(".uneteEvent").hide();
            $(".uneteAbEvent").hide();
            var activo = 1;
            $.ajax({
                url: '/grupo/index/unir',
                type: 'get',
                data: 'act=' + activo +'&idE='+even,
                dataType: "json",
                success: function(data){
                    $(".img-lo").hide();
                    $(".uneteAbEvent").show();                    
                    var dataPer = '<li>'+
                                    '<div class="users">'+
                                        '<div class="row-fluid">'+
                                            '<div class="span4 img-user-ev">'+
                                                '<img src="'+data.userestado["imagen"]+'" alt="">'+
                                            '</div>'+
                                            '<div class="span8 desc-user">'+
                                                '<h3><a href="#">'+data.userestado["nombre_usuario"]+'</a></h3>'+
                                                '<p>'+data.userestado["descripcion_usuario"]+'</p>'+
                                            '</div>'+
                                        '</div>'+
                                        '<div class="row-fluid unio">'+
                                            '<p class="span12">'+data.userestado["va_fecha"]+'</p>'+
                                        '</div>'+
                                    '</div>'+
                                    '</li>';
                    $(".lista-usuario ul").prepend(dataPer);
                },
                error: function(){
                    console.log('Fallo conectando con el servidor')
                }
            });
        });
    }

    function abandonarDatos(){
        var even = <?php echo $this->in_id; ?>;
        $(".uneteAbEvent").on('click', function(e){
            e.preventDefault();
            var addLoading = '<img class="img-lo" src="/img/cargando.gif" />';
            $(".unete-grupo").append(addLoading);
            $(".uneteAbEvent").hide();
            $(".uneteEvent").hide();
            var activo = 0;
            $.ajax({
                url: '/grupo/index/unir',
                type: 'get',
                data: 'act=' + activo +'&idE='+even,
                dataType: "json",
                success: function(data){
                    $(".img-lo").hide();
                    $(".uneteEvent").show();
                    $(".lista-usuario ul li:first-child").remove();
                },
                error: function(){
                    console.log('Fallo conectando con el servidor')
                }
            });
        });
    }

</script>