<script type="text/javascript">
<!--
var fecha_actual='<?php echo date("Y-m-d H:i:s");?>';
//-->
</script>
<div class="main-container">
    <div class="container">
        <div class="row-fluid crear-grupos">
			<?php
			$title = 'Editar grupo';
			$this->headTitle($title);
			$form = $this->form;
			$form->setAttributes(array(
			    'action' => $this->url.'/grupo/index/editargrupo/'.$this->in_id,
			    'method' => 'post',
			    'class'=>'form-crear-grupo'
			));

			$form->prepare();
			echo $this->form()->openTag($form);
			?>
			<div class="row-fluid">
                <div class="span12 crear-evento event box">
                    <h1>Edita tu grupo</h1>
                    <p>¡Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy!</p>
                </div>
            </div>

			<div class="row-fluid event nmb box">
                <div class="span8 space-group">
                    <input type="hidden" name="url" value="<?php echo $this->urlorigen?>"/>
                    <?php echo $this->formHidden($form->get('in_id'));?>
                    <?php echo $this->formRow($form->get('va_nombre'));?>
                    <?php echo $this->formRow($form->get('ta_categoria_in_id'));?>
                    <?php echo $this->formRow($form->get('va_pais'));?>
                    <?php echo $this->formRow($form->get('va_ciudad'));?>
                    <?php echo $this->formRow($form->get('va_descripcion'));?>
                </div>
                <div class="span4 space-group">
                    <div class="control-group">
                        <label for="textfield" class="control-label"></label>
                        <div class="controls">
                            <div class="fileupload fileupload-new" data-provides="fileupload">
                                <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
                                    <?php if($this->imagen=='defaultd.jpg'){ ?>
                                    <img src="<?php echo $this->host('img')?>/defaultd.jpg" />
                                    <?php   }else { ?>                                 
                                    <img src="<?php echo $this->host('images') . '/grupos/general/' .$this->escapeHtml($this->imagen); ?> " />
                                     <?php   } ?>
                                </div>
                                <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                                <div>
                                    <span class="btn btn-file">
                                        <span class="fileupload-new">Seleccionar una imagen</span>
                                        <span class="fileupload-exists">Cambiar</span>
                                       <?php echo $this->formRow($form->get('va_imagen'));?>
                                    </span>
                                    <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Eliminar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

			<p class="crear-evento box">
                <?php echo $this->formSubmit($form->get('submit'));?>
                <a href="" class="btn btn-inverse btn-cancelar">Cancelar</a>
            </p>
			<?php echo $this->form()->closeTag();?> 

		</div>
    </div>
</div> <!-- #main-container -->

<script type="text/javascript">
    var cboPais = $("#pais");
    var distriJ = $("#va_ciudad");
    cboPais.change(function(){
        var hi = cboPais.val();
        if(hi === ''){
            var inp = '<option value="">--- Seleccionar ---</option>';
            distriJ.empty();
            distriJ.append(inp);
        }else{
            var valPais =  $(this).find('option:selected').val();
            $.ajax({
                url: "/usuario/index/jsonciudad?code=" + valPais , 
                cache:true,
                data: {},
                success: function(nselect){
                    var data = JSON.parse(nselect || {});
                    var departList = [];
                    distriJ.empty();
                    for (var key in data) {
                        dataF = data[key];
                        var keyL = dataF.ID;
                        var val = dataF.Name;
                        var  departItem = '<option value="'+ keyL +'">'+ val +'</option>';
                        departList.push(departItem);
                    }
                    var joinDep = departList.join('');
                    distriJ.append(joinDep);
                }
            });
        }
    });
</script>