        <!--<div class="filtrar-home">
            <div class="container">
                <div class="row-fluid">
                    <div class="span12" id="bar">
                        <table class="filter">
                            <tbody>
                                <tr>
                                    <td><input type="radio" name="category" value="all" checked="checked"/></td>
                                    <td><label>Toda las categorias</label></td>
                                </tr>
                                    <td><input type="radio" name="category" value="web"/></td>
                                    <td><label>Arte</label></td>
                                </tr>
                                <tr>
                                    <td><input type="radio" name="category" value="grafica"/></td>
                                    <td><label>Campamentos</label></td>
                                </tr>
                                <tr>
                                    <td><input type="radio" name="category" value="art"/></td>
                                    <td><label>Musica</label></td>
                                </tr>
                                <tr>
                                    <td><input type="radio" name="category" value="3d"/></td>
                                    <td><label>Desarrollador</label></td>
                                </tr>
                                <tr>
                                   <td><input type="radio" name="category" value="foto"/></td>
                                    <td><label>Conferencias</label></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>-->

        <div class="main-container">
            <div class="container">
                <div class="row-fluid">
                    <div class="span12 main wrapper" id="content" data-ui-scrollbar>
                        <ul>
                            <div><?php echo $this->dato;?></div>        
                            <?php if($this->grupos =='' ) { 
                   
                            foreach ($this->eventos  as $eventos) :?>
                            <li data-category="web">
                                <a href="ficha-producto.html" class="preview" data-ui-lightbox>
                               <img src="<?php   echo $this->host('images') . '/eventos/general/' . htmlspecialchars($eventos->va_imagen, ENT_QUOTES, 'utf-8');  ?>">
                                </a>
                                <div class="content">
                                    <div class="info">
                                        <span><?php  $fecha = date_create($eventos->va_fecha);
                                         echo $fecha = date_format($fecha, 'd/m/Y'); ?></span>
                                        <span class="category">
                                            <a href="#"><?php echo  $this->escapeHtml($eventos->nombre_categoria);?></a>
                                        </span>
                                        </span>
                                    </div>
                                    <h2>
                                        <a href="/grupo/evento/detalle?id=<?php echo $this->escapeHtml($eventos->in_id); ?>"><?php echo $this->escapeHtml($eventos->va_nombre); ?></a>
                                    </h2>
                                    <p>
                                       <?php echo  $this->escapeHtml($eventos->va_descripcion);?>
                                    </p>
                                </div>
                            </li>
                            <?php endforeach; } else  { foreach ($this->grupos  as $grupos) :?>
                            <li data-category="web">
                                <a href="ficha-producto.html" class="preview" data-ui-lightbox>
                               <img src="<?php   echo $this->host('images') . '/grupos/general/' . htmlspecialchars($grupos->va_imagen, ENT_QUOTES, 'utf-8');  ?>">
                                </a>
                                <div class="content">
                                    <div class="info">
                                        <span><?php  $fecha = date_create($grupos->va_fecha);
                                         echo $fecha = date_format($fecha, 'd/m/Y'); ?></span>
                                        <span class="category">
                                            <a href="#"><?php echo  $this->escapeHtml($grupos->nombre_categ);?></a>
                                        </span>
                                        </span>
                                    </div>
                                    <h2>
                                        <a href="/grupo/index/detallegrupo"><?php echo $this->escapeHtml($grupos->va_nombre); ?></a>
                                    </h2>
                                    <p>
                                       <?php echo  $this->escapeHtml($grupos->va_descripcion);?>
                                    </p>
                                </div>
                            </li>
                            <?php endforeach;} ?> 
                                    
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div> <!-- #main-container -->


