<div class="page-container">
	<div class="container">
		<div class="row-fluid">
			<div class="span12 page-juntate crear-evento-1 box">
				<h3>¿QUÉ ES JUNTATE.PE?</h3>
				<p>Junatate.pe es un sitio en el que podrás publicar y encontrar personas con tus mismas aficiones.</p>
				<h3>¿Cómo lo uso?</h3>
				<p>La forma de uso es simple:</p>
				<ol>
					<li>Regístrate con tu correo electrónico y activa la cuenta con el correo de confirmación.</li>
					<li>Crea los grupos de tu interés y eventos que desees realizar con los miembros del grupo.</li>
					<li>Invita a tus amigos a través del Facebook o correo electrónico para que se unan a tus eventos.</li>
					<li>Busca eventos o grupos de tu interés y únete a ellos.</li>
				</ol>
				<h3>Portada</h3>
				<p>En nuestra portada se mostrarán los últimos eventos creados, así como los grupos con los últimos eventos creados, puedes ingresar a ellos para visualizar su información.</p>
				<h3>Mi perfil</h3>
				<p>Una vez registrado puedes acceder a la información de tu cuenta como: datos de tu cuenta, tus grupos y eventos creados y los grupos y eventos a los que te has unido.</p>
			</div>
		</div>
	</div>
</div>