<div class="page-container">
	<div class="container">
		<div class="row-fluid">
			<div class="span12 page-juntate crear-evento-1 box">
				<h3>Términos y condiciones de uso</h3>
				<p>Los términos y condiciones de Juntate.pe rigen tu acceso y uso a los servicios que ofrece la empresa Innovations Systems Group S.A.C. de su sitio web y aplicación móvil juntate.pe (en adelante el "sitio"). Al acceder, usar e inscribirte al sitio como usuario estás aceptando y dando conformidad a los presentes Términos y Condiciones de Uso. Por tanto, no accedas ni uses el sitio si no estás enteramente de acuerdo.
				</p>
				<h3>Cambios en las condiciones del servicio</h3>
				<p>
				Podemos modificar las condiciones en el momento que consideremos oportuno. Entiendes que aceptas las condiciones que rigen en el momento de tu acceso.
				</p>
				<h3>Uso del sitio</h3>
				<p>Puedes usar el sitio sujeto a las condiciones del servicio.</p>
				<p>El sitio puede ser modificado, actualizado, interrumpido, suspendido o eliminado en cualquier momento sin previo aviso.</p>
				<p>El registro como usuario será mediante tu nombre y un correo electrónico, mediante el cual puedes crear grupos, eventos y participar en grupos y eventos creados por otros usuarios. Es de tu responsabilidad usar tu propio nombre y cuenta de correo para reforzar tu credibilidad. Nos reservamos el derecho de cerrar tu cuenta en cualquier momento si observamos una conducta inapropiada.</p>
				<p>Al crear una cuenta aceptas recibir comunicaciones del sitio.</p>
				<h3>Grupos y Eventos</h3>
				<p>La información de los Grupos y Eventos creados no son asumidos como nuestra responsabilidad. El sitio podrá desactivarlos cuando los considere "no adecuados" o cuando sean denunciados.</p>
			</div>
		</div>
	</div>
</div>