<div class="row-fluid crear-evento-grupos" style="display:none;">
            <?php
        $formevento = $this->formevento;

        $formevento->setAttributes(array(
            'action' => $this->url.'/grupo/evento/agregarevento',
            'method' => 'post',
            'class'=>'span12 form-crear-grupo',
            'id'=>'crearEventoGñññññ'
        ));

        $formevento->prepare();
        echo $this->form()->openTag($formevento);
        ?>
        <div class="row-fluid">
            <div class="span12 crear-evento event">
                <h1>Crear un nuevo evento</h1>
                <p>¡Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy!</p>
            </div>
        </div>
        <div class="row-fluid crear-evento-1 event">
            <h2>Describe tu evento</h2>
            <div class="span8 desc-evento">
                <?php echo $this->formRow($formevento->get('va_nombre'));?>
                <label>Descripción del evento:</label>
                <?php echo $this->formRow($formevento->get('va_descripcion'));?>
                <!--<textarea class="ckeditor" cols="80" id="editor1" name="editor1" rows="10"></textarea>-->
            </div>
            <div class="span4">
                <div class="control-group">
                    <label for="textfield" class="control-label"></label>
                    <div class="controls">
                        <div class="fileupload fileupload-new" data-provides="fileupload">
                            <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
                                <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" />
                            </div>
                            <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                            <div>
                                <span class="btn btn-file"><span class="fileupload-new">Select image</span><span class="fileupload-exists">Change</span>
                                   <?php echo $this->formRow($formevento->get('va_imagen'));?>
                                </span>
                                <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row-fluid crear-evento-2 event">
            <h2>Cuando? y Cuanto sera el precio.</h2>
            <div class="span3 fecha event-padding">
                <div class="form_row">
                    <label class="field_name">Fecha y hora:</label>
                    <div class="field">
                        <div class="span10 input-append date form_datetime2" data-date="2013-02-21T15:25:00Z">
                            <?php echo $this->formRow($formevento->get('va_fecha'));?>
                            <span class="add-on"><i class="icon-remove"></i></span>
                            <span class="add-on"><i class="icon-calendar"></i></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="span3">
                <label class="field_name">Duración del evento:</label>
                <div class="input-prepend input-append">
                    <span class="add-on"><i class="icon-time"></i></span>
                    <?php echo $this->formRow($formevento->get('va_duracion'));?>
                    <span class="add-on">Horas</span>
                </div>
            </div>
            <div class="span3">
                <label class="field_name">Precio referencial para el evento:</label>
                <div class="input-prepend input-append">
                    <span class="add-on">S/.</span>
                     <?php echo $this->formRow($formevento->get('va_costo'));?>
                    <span class="add-on">.00</span>
                </div>
            </div>
            <div class="span3">
                <div class="control-group span5">
                  <label class="control-label" for="inputIcon">Minimo:</label>
                  <div class="controls">
                    <div class="input-prepend">
                      <span class="add-on"><i class="icon-envelope"></i></span>
                      <?php echo $this->formRow($formevento->get('va_min'));?>
                    </div>
                  </div>
                </div>
                <div class="control-group span5">
                  <label class="control-label" for="inputIcon">Maximo:</label>
                  <div class="controls">
                    <div class="input-prepend">
                      <span class="add-on"><i class="icon-envelope"></i></span>
                      <?php echo $this->formRow($formevento->get('va_max'));?>
                    </div>
                  </div>
                </div>
            </div>
        </div>
        <div class="row-fluid crear-evento-3 event">
            <h2>Elige el lugar del evento</h2>
            <div class="span12 event-padding dev-padd">
                <div id="map" style="border:1px solid #eee;"></div>
            </div>
            <div class="span3 lugar-nm event-padding">
                <div class="form-item">
                    <div id="cityId-label" class="item-label">
                        <label for="cityId" class="required">Ciudad</label>
                    </div>
                    <div class="item-value">
                        <?php echo $this->formRow($formevento->get('ta_ubigeo_in_id'));?>
<!--                        <select name="cityId" id="cityId" class="input-block-level">
                            <option value="PER-LIM" label="Lima, Perú" selected="selected">Lima, Perú</option>
                        </select>-->
                    </div>
                </div>       
            </div>
            <div class="span5">
                <div class="form-item tooltip-errors">
                    <div id="address-label" class="item-label">
                        <label for="address" class="required">Dirección</label>
                    </div>
                    <div class="item-value">
                        <?php echo $this->formRow($formevento->get('va_direccion'));?>
                       
                    </div>
                </div>      
            </div>
            <div class="span3">
                <div class="form-item tooltip-errors">
                    <div id="addressReference-label" class="item-label">
                        <label for="addressReference" class="optional">Referencia de ubicación</label>
                    </div>
                    <div class="item-value">
                         <?php echo $this->formRow($formevento->get('va_referencia'));?>                      
                    </div>
                </div>
                <?php echo $this->formRow($formevento->get('va_latitud'));?>
                <?php echo $this->formRow($formevento->get('va_longitud'));?>       
            </div>
        </div>
        <p class="crear-evento">
            <?php echo $this->formSubmit($formevento->get('submit'));?>
        </p>
            <?php echo $this->form()->closeTag();?>
</div>