<div class="event-comentario">
    <!-- FORMULARIO COMENTARIO-->
 <div class="row-fluid">
  <?php if($this->session && $this->grupoestado=='activo'){?>
      
   <?php $fecha_actual = date("Y-m-d h:m:s"); 
    if ( $this->eventos[0]['va_fecha'] >= $fecha_actual)
    {?> 
    <div class="span12 comentar-form">
      <h4><?php echo ucwords($this->session->va_nombre);?>, ¡Comente aquí!</h4>
  <?php
    $form = $this->comentarioform;

    $form->setAttributes(array(
        'action' =>'grupo/evento/comentarios'.$this->idevento,
        'method' => 'post',
        'id'=>'form-comente'
    ));

    $form->prepare();
    echo $this->form()->openTag($form);
  ?>
        <div class="row-fluid fn-form">
          <div class="span2">
            <img src="../../img/foto-carnet.jpg" alt="">
          </div>
          <div class="span10">
          <?php echo $this->formRow($form->get('va_descripcion'));?>
          </div>
          <p>
          <?php echo $this->formSubmit($form->get('submit'));?>
          </p>
        </div>
            <?php echo $this->form()->closeTag();?>
    </div>
      
      <?php  }?>            
     <?php }elseif(!$this->grupocomprueba){?>
     <div class="span12 login-comentario">
      <p>Debes de unirte al evento para comentar.</p>
    </div>
     
    <?php }else{?>
    <div class="span12 login-comentario">
      <p><a href="#inline_evento" class="inlineEventoDet">Iniciar session</a> para comentar.</p>
    </div>
    <?php }?>
  </div>
<!-- FIN DE FORMULARIO COMENTARIO-->
<div class="row-fluid cometarios-detalle">
   
<!--  LISTADO COMENTARIOS -->
<!-- FIN DE LISTADO COMENTARIOS-->
  </div>
</div>
