<div class="event-comentario">
                    <!-- FORMULARIO COMENTARIO-->
                 <div class="row-fluid">
                  <?php if($this->session && $this->grupocomprueba){?>
                      
                   <?php $fecha_actual = date("Y-m-d h:m:s"); 
                    if ( $this->eventos[0]['va_fecha'] >= $fecha_actual)
                    {?> 
                    <div class="span12 comentar-form">
                      <h4><?php echo ucwords($this->session->va_nombre);?>, ¡Comente aqui!</h4>
                <?php
                    $form = $this->comentarioform;
            
                    $form->setAttributes(array(
                        'action' =>'grupo/evento/comentarios'.$this->idevento,
                        'method' => 'post',
                        'id'=>'form-comente'
                    ));
            
                    $form->prepare();
                    echo $this->form()->openTag($form);
                 ?>
                        <div class="row-fluid fn-form">
                          <div class="span2">
                            <img src="../../img/foto-carnet.jpg" alt="">
                          </div>
                          <div class="span10">
                          <?php echo $this->formRow($form->get('va_descripcion'));?>
                          </div>
                          <p>
                          <?php echo $this->formSubmit($form->get('submit'));?>
                          </p>
                        </div>
                            <?php echo $this->form()->closeTag();?>
                    </div>
                      
                      <?php  }?>            
                     <?php }elseif(!$this->grupocomprueba){?>
                     <div class="span12 login-comentario">
                      <p>Debes de unirte al evento para comentar.</p>
                    </div>
                     
                    <?php }else{?>
                    <div class="span12 login-comentario">
                      <p><a href="#inline_evento" class="inlineEventoDet">Iniciar session</a> para comentar.</p>
                    </div>
                    <?php }?>
                  </div>
                  <!-- FIN DE FORMULARIO COMENTARIO-->
                  <div class="row-fluid cometarios-detalle">
                    <ul>
                        <?php  foreach ($this->comentarios  as $comentarios) :?>
                      <li> 
                        <div class="content-comentario">
                          <div class="span2">
                       <?php if(($comentarios->imagen)!="foto-carnet.jpg"){?>
                     <img src="<?php echo $this->host('images') ?>/usuario/comentarios/<?php echo $comentarios->imagen ;?>" alt="">
                     <?php }else{?>
                      <img src="<?php echo $this->host('img') ?>/foto-carnet.jpg" alt="">
                      <?php }?>
                          </div>
                          <div class="span10 ti-coment">
                            <h4><a href="#"><?php echo  $this->escapeHtml($comentarios->nombre_usuario);?></a></h4>
                            <p><?php echo  $this->escapeHtml($comentarios->va_descripcion);?></p>
                            <p class="small muted">
                             <?php  $fecha = date_create($this->escapeHtml($comentarios->va_fecha));
                                         $arrayMeses = array('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
                echo date_format($fecha, "d").' de '. $arrayMeses[date('m')-1].' del '.date_format($fecha, "Y"); ?>
                            </p>
                          </div>
                        </div>
                      </li>
                       <?php endforeach;  ?>
                    </ul>
<!-- FIN DE LISTADO COMENTARIOS-->
                  </div>
                </div>