<div class="main-container">
    <div class="container">
        <div class="row-fluid">
            <div class="span3 group-sidebar">
                <div class="img-grupo">
                    <img src="<?php   echo $this->host('images') . '/grupos/general/' . htmlspecialchars($this->eventos[0]['imagen'], ENT_QUOTES, 'utf-8');  ?>">
                </div>
                <h2 class="gh"><a href="#"><?php echo $this->eventos[0]['nombre_grupo']; ?>  </a></h2>
                <p class="fund gh"><em>Fundado el <?php  $fecha = date_create($this->eventos[0]['fecha_creacion']);
                                         echo $fecha = date_format($fecha, "d \d\e\l m \d\e\l Y"); ?></em></p>
                <p class="desc gh">
                  <?php echo $this->eventos[0]['descripcion']; ?> <br> <a href="#">Ver mas...</a>
                </p>
                <p class="gh ft"><a class="dp" href="#"><span class="cant-user ab">Nº Usuarios</span> <span class="nm"><?php echo $this->grupo[0]['cantidad']; ?></span></a></p>
                <p class="gh ft"><a class="dp" href="#"><span class="cant-evento-f ab">Evento futuros</span> <span class="nm"><?php echo $this->eventosfuturos[0]['eventosfuturos']; ?></span></a></p>
                <p class="gh ft"><a class="dp" href="#"><span class="cant-evento-p ab">Evento pasados</span> <span class="nm"><?php echo $this->eventospasados[0]['eventospasados']; ?></span></a></p>
            </div>
            <div class="span6">
                <div class="event-group">
                    <h1><?php echo $this->eventos[0]['va_nombre']; ?></h1>
                    <div class="asig-evento">
                        <ul>
                            <li>
                                <div class="ficha-dep">
                                    Organizador:  
                                </div>
                                <div class="ficha-desc">
                                   <?php echo $this->eventos[0]['nombre_user']; ?>
                                </div>
                            </li>
                            <li>
                                <div class="ficha-dep">
                                    Fecha y hora:  
                                </div>
                                <div class="ficha-desc">
                                    <p><?php  $fecha = date_create($this->eventos[0]['va_fecha']);
                                         echo $fecha = date_format($fecha, "d \d\e\l m \d\e\l Y"); ?></p>
                                    <em><?php  $fecha = date_create($this->eventos[0]['va_fecha']);
                                          $hora = date_format($fecha, 'h:m');
                                                  if($hora<12)
                                                  { echo $hora.' AM'; }
                                                  else
                                                      { echo $hora.' PM'; }
                                         ?></em>
                                </div>
                            </li>
                            <li>
                                <div class="ficha-dep">
                                    Duración:  
                                </div>
                                <div class="ficha-desc">
                                   <?php echo $this->eventos[0]['va_duracion']; ?> Horas
                                </div>
                            </li>
                            <li>
                                <div class="ficha-dep">
                                    Precio:  
                                </div>
                                <div class="ficha-desc">
                                    S/. <?php echo $this->eventos[0]['va_costo']; ?>
                                </div>
                            </li>
                            <li>
                                <div class="ficha-dep">
                                    Categoría:  
                                </div>
                                <div class="ficha-desc">
                                    <?php echo $this->eventos[0]['nombre_categoria']; ?>  
                                </div>
                            </li>
                            <li>
                                <div class="ficha-dep">
                                    Dirección:  
                                </div>
                                <div class="ficha-desc">
                                    <p>   <?php echo $this->eventos[0]['va_direccion']; ?> </p>
                                    <em>Lima, Lima (<a href="#">Mapa</a>)</em>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="mapa-group map-wrapper">
                        <div id="map_canvas"></div>
                    </div>
                    <div class="desc-evento-g">
                        <div id="event-description-wrap" itemprop="description" class="line">
                            <p><?php echo $this->eventos[0]['va_descripcion']; ?></p>
                         <p>The circuit from above:</p>
                        <p>
                            <img src="http://static.wix.com/media/63ce3d_af2d42b6f3828b3d53767f1093c42cc3.png_srz_949_506_75_22_0.50_1.20_0.00_png_srz" style="max-width:100%;margin:5px">
                        </p>
                        <p>Pictures of the circuit:</p>
                        <p>
                            <img src="http://static.wix.com/media/63ce3d_b83d2d3eb3b28bc72f204c569de69943.jpg_srz_460_287_75_22_0.50_1.20_0.00_jpg_srz" style="max-width:100%;margin:5px"> 
                            <img src="http://static.wix.com/media/63ce3d_f75aa780a3182c65014c8c3cadd99a61.jpg_srz_695_525_75_22_0.50_1.20_0.00_jpg_srz" style="max-width:100%;margin:5px"> 
                            <img src="http://static.wix.com/media/63ce3d_b39f7e64a8d0cdeddcc41ed9271075f5.jpg_srz_635_490_75_22_0.50_1.20_0.00_jpg_srz" style="max-width:100%;margin:5px"> 
                            <img src="http://static.wix.com/media/63ce3d_0e11fc78c2f0df36af448cb3914c2600.jpg_srz_335_525_75_22_0.50_1.20_0.00_jpg_srz" style="max-width:100%;margin:5px"> 
                            <img src="http://static.wix.com/media/63ce3d_f806e135f715622d60865cedc00f9bc0.jpg_srz_480_375_75_22_0.50_1.20_0.00_jpg_srz" style="max-width:100%;margin:5px">
                        </p>

                        </div>
                    </div>
                </div>
                <div class="event-comentario">
                  <div class="row-fluid">
                    <div class="span12 comentar-form">
                      <h4>Jesser, ¡Comente aqui!</h4>
                      <form action="" id="form-comente" name="form-comente">
                        <div class="row-fluid fn-form">
                          <div class="span2">
                            <img src="../../img/avatar.jpg" alt="">
                          </div>
                          <div class="span10">
                            <textarea name="texto-comentar" id="texto-comentar" cols="30" rows="5" placeholder="Ingrese su comentario aquí."></textarea>
                          </div>
                          <p>
                            <input type="text" class="btn btn-primary" value="Comentar" />
                          </p>
                        </div>
                      </form>
                    </div>
                    <!--<div class="span12 login-comentario">
                      <p><a href="#">Iniciar session</a> para comentar.</p>
                    </div>-->
                  </div>
                  <div class="row-fluid cometarios-detalle">
                    <ul>
                        <?php  foreach ($this->comentarios  as $comentarios) :?>
                      <li> 
                        <div class="content-comentario">
                          <div class="span2">
                            <img src="<?php   echo $this->host('images') . '/usuario/principal/' . $this->escapeHtml($comentarios->imagen)  ?>" alt="">
                          </div>
                          <div class="span10 ti-coment">
                            <h4><a href="#"><?php echo  $this->escapeHtml($comentarios->nombre_usuario);?></a></h4>
                            <p><?php echo  $this->escapeHtml($comentarios->va_descripcion);?></p>
                            <p class="small muted">
                             <?php  $fecha = date_create($this->escapeHtml($comentarios->va_fecha));
                                         echo $fecha = date_format($fecha, "d \d\e\l m \d\e\l Y"); ?>
                            </p>
                          </div>
                        </div>
                      </li>
                       <?php endforeach;  ?>
                    </ul>
                  </div>
                </div>
            </div>
            <div class="span3">
              <div class="asistir-event">
                <div class="row-fluid">
                  <form action="" class="span12 form-asistir">
                    <div class="row-fluid">
                      <h4>¿Asistiras?</h4>
                      <label class="radio inline">
                        <input type="radio" name="asistirGrupo" id="asistirGrupo1" value="option1" checked="">
                          Si
                      </label>
                      <label class="radio inline">
                        <input type="radio" name="asistirGrupo" id="asistirGrupo2" value="option1">
                          No
                      </label>
                    </div>
                    <div class="row-fluid">
                      <div class="span12 btn-unete">
                        <button type="submit" class="btn btn-success">Unete al evento</button>
                      </div>
                    </div>
                  </form>
                </div>
               </div>
               <div class="lista-usuario">
                  <ul>
                    <li>
                      <div class="users">
                         <?php  foreach ($this->usuarios  as $usuarios) :?>
                        <div class="row-fluid">
                            <div class="span4 img-user-ev">
                               <img src="<?php   echo $this->host('images') . '/usuario/principal/' . htmlspecialchars($usuarios->imagen, ENT_QUOTES, 'utf-8');  ?>" alt="">
                            </div>
                            <div class="span8 desc-user">
                                <h3><a href="#"><?php echo  $this->escapeHtml($usuarios->nombre_usuario);?></a></h3>
                               <p><?php echo  $this->escapeHtml($usuarios->descripcion_usuario);?></p>
                            </div>
                        </div>
                        <div class="row-fluid unio">
                           <p class="span12">Se unio el <?php  $fecha = date_create($this->escapeHtml($usuarios->va_fecha));
                                         echo $fecha = date_format($fecha, "d \d\e\l m \d\e\l Y"); ?></p>
                        </div>
                          <?php endforeach;  ?>
                      </div>
                    </li>
                  </ul>
               </div>
            </div>
        </div>
    </div>
</div> <!-- #main-container -->