<!--<div id="fb-root"></div>
  <script type="text/javascript">
    (function(d) {
        var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
        if (d.getElementById(id)) {
            return;
        }
        js = d.createElement('script');
        js.id = id;
        js.async = true;
        js.src = "//connect.facebook.net/en_US/all.js";
        ref.parentNode.insertBefore(js, ref);
    }(document));

    window.fbAsyncInit = function() {
        FB.init({
            appId: '353959668068919', 
            status: true, 
            cookie: true, 
            xfbml: true  
        });
    };
</script>-->
<?php if(!$_GET['m']){ ?>
<div class="main-container">
    <div class="container">
        <?php if ($this->mensajes) { ?>
          <div class="row-fluid">
            <div class="alert alert-success alert-margin">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <?php
              foreach ($this->mensajes as $message) {
                  echo $message;
              }
              ?>
            </div>
          </div>
        <?php } ?>
        <div class="row-fluid">
            <div class="span3 group-sidebar" style="padding-bottom:15px;">
              <div class="img-grupo">
                <a href="/grupo/index/detallegrupo/<?php echo $this->escapeHtml($this->eventos[0]['id_grupo'], ENT_QUOTES, 'utf-8');  ?>">
                    
                    
                    <?php  if($this->eventos[0]['imagen']=='defaultd.jpg') { ?>
           <img src="<?php echo $this->host('img') ?>/defaultd.jpg">
              <?php  } else {?>
           <img src="<?php echo $this->host('images') . '/grupos/general/' . htmlspecialchars($this->eventos[0]['imagen'], ENT_QUOTES, 'utf-8');  ?>">
                  <?php   }  ?>
                
                </a>
              </div>
             
              <h2 class="gh"><a href="<?php echo $this->url('detalle-grupo').'/'.$this->escapeHtml($this->eventos[0]['id_grupo'], ENT_QUOTES, 'utf-8');  ?>"><?php echo $this->eventos[0]['nombre_grupo']; ?>  </a></h2>
              <p class="fund gh">
                <em>Fundado el <?php $fecha = date_create($this->eventos[0]['fecha_creacion']); 
                $arrayMeses = array('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
                echo date_format($fecha, "d").' de '. $arrayMeses[date('m')-1].' del '.date_format($fecha, "Y"); ?></em>
              </p>
              <p class="desc gh">
                <?php echo $this->eventos[0]['descripcion']; ?> <br>
              </p>
              <p class="gh ft"><span class="cant-user ab">Nº Usuarios</span> <span class="nm"><?php echo $this->grupo[0]['cantidad']; ?></span></p>
              <p class="gh ft"><span class="cant-evento-f ab">Evento futuros</span> <span class="nm"><?php echo $this->eventosfuturos[0]['eventosfuturos']; ?></span></p>
              <p class="gh ft">
                <span class="cant-evento-p ab">Evento pasados</span> 
                <span class="nm"><?php echo $this->eventospasados[0]['eventospasados']; ?></span>
              </p>
              <!--<h3 class="title-si">Organizador</h3>
              <ul>
                <li><a href="#">Jesser pariona</a></li>
              </ul>-->
            </div>
            <div class="span6 group-sidebar">
         <?php if($this->eventos[0]['va_tipo']=='privado'){ 
              if($this->grupoestado=='activo'){?>
                 <div class="event-group">
                  <div class="content-img-det">
                 <?php  if($this->eventos[0]['va_imagen']=='defaultd.jpg') { ?>       
                    <img class="det-img" src="<?php echo $this->host('img')?>/defaultd.jpg" title="Evto macabro" target="Evento macabro">
                   <?php  } else { ?>
             <img class="det-img" src="<?php echo $this->host('images') . '/eventos/detalle/' . $this->escapeHtml($this->eventos[0]['va_imagen'])  ?>" title="Evto macabro" target="Evento macabro">
                <?php  }  ?>
 <?php if($this->eventos[0]['ta_usuario_in_id']==$session->in_id){?>
                    <div class="content-edit">
                      <a href="/evento/editar/<?php echo $this->idevento?>" title="Editar detalle de evento">
                        <img src="/img/edit.png">
                      </a>
                    </div>
                    <?php } ?>
                  </div>
                   <?php $fecha_actual = date("Y-m-d h:m:s"); 
                    if ( $this->eventos[0]['va_fecha'] >= $fecha_actual)
                    {}
                   else{?> <h2 class="event-caducado">EVENTO CADUCADO</h2> <?php } ?> 
                    <div class="review-block">
                      <div class="overall_score">
                        <h1 class="title-ji"><?php echo $this->eventos[0]['va_nombre']; ?></h1>
                        <ul class="score-list">
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Organizador:  
                            </div>
                            <div class="ficha-desc">
                               <?php echo $this->eventos[0]['nombre_user']; ?>
                            </div>
                          </li>
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Fecha y hora:  
                            </div>
                            <div class="ficha-desc">
                              <p><?php $fecha = date_create($this->eventos[0]['va_fecha']); 
                              $arrayMeses = array('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                              'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
                              echo date_format($fecha, "d").' de '. $arrayMeses[date('m')-1].' del '.date_format($fecha, "Y"); ?></p>
                              <em><?php  $fecha = date_create($this->eventos[0]['va_fecha']);
                                    $hora = date_format($fecha, 'H');
                                  if($hora<12)
                                  { echo date_format($fecha, 'h').':'. date_format($fecha, 'i').' AM'; }
                                  else
                                   { echo date_format($fecha, 'h').':'. date_format($fecha, 'i').' PM'; }

                                ?></em>
                            </div>
                          </li>
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Duración:  
                            </div>
                            <div class="ficha-desc">
                             <?php echo $this->eventos[0]['va_duracion']; ?> Horas
                            </div>
                          </li>
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Precio:  
                            </div>
                            <div class="ficha-desc">
                              S/. <?php echo $this->eventos[0]['va_costo']; ?>
                            </div>
                          </li>
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Categoría:  
                            </div>
                            <div class="ficha-desc">
                              <?php echo $this->eventos[0]['nombre_categoria']; ?>  
                            </div>
                          </li>
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Dirección: 
                              <br>
                              <em>
                               referencia:
                               </em>
                            </div>
                           
                            <div class="ficha-desc">
                              <p><?php echo $this->eventos[0]['va_direccion']; ?></p>
                              <em>(<?php echo $this->eventos[0]['va_referencia']; ?>)</em>
                            </div>
                          </li>
                        </ul> <!-- /score-list -->
                      <div class="clear"></div>
                    </div>  <!-- /overall_score -->  
                  </div>
                  <?php if($this->grupoestado=='activo' && $this->privado==true){ ?>
                 <div class="invitar-amigos">
                    <div class="accordion" id="accordion2">
                      <div class="accordion-group">
                        <div class="accordion-heading">
                          <a class="accordion-toggle invitar" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                            Invitar amigos
                            <img src="/img/add.png">
                          </a>
                        </div>
                        <div id="collapseOne" class="accordion-body collapse">
                          <div class="accordion-inner">
                              <div id="invita-correo">
                                <div class="row-fluid">
                                    <?php if($this->mensaje_correo){?>
                                   <div class="row-fluid">
                                        <div class="alert alert-success alert-margin">
                                          <?php echo $this->mensaje_correo;?>
                                        </div>
                                      </div>
                                    <?php }?>
                                  <div class="span6">
                                    <form method="post" action="/grupo/evento/invitar" id="form-correo-s">
                                      <input type="hidden" name="idE" value="<?php echo $this->idevento;?>"/>
                                        <h3>Ingresa correos separado por comas</h3>
                                      <em>Ejm: example@gmail.com, ejemplo@gmail.com</em>
                                      <input type="text" name="correos" class="inputModif"/>
                                      <input type="submit" class="btn btnCorreoForm" name="Enviar"/>
                                    </form>
                                  </div>
                                  <div class="span6">
                                    <div class="span12 user-back-2 email-user-d">
                                      <form method="post" action="/grupo/evento/invitar" id="gruposInvitar">
                                          <input type="hidden" name="idE" value="<?php echo $this->idevento;?>"/>
                                        <h3>Elige a todo tus amigos para enviarles correo de invitación al evento.</h3>
                                        <ul>
                                            <?php foreach($this->grupoeventusuario as $grupousuario){?>
                                                <li id="user-<?php echo $grupousuario->idusuario;?>">
                                                <input class="enviar_correo" name="userEnviar[]" value="<?php echo $grupousuario->idusuario;?>" type="checkbox"> 
                                                <label class="checkbox img-cargar-usuarios">
                                                  <img src="<?php echo $this->host('images')?>/usuario/perfil/<?php echo $grupousuario->imagen;?>" title="<?php echo $grupousuario->nombre_usuario;?>">
                                                  <a href="/usuario/<?php echo $grupousuario->idusuario;?>"><?php echo $grupousuario->nombre_usuario;?></a> 
                                                  <p><?php echo $grupousuario->descripcion_usuario;?></p>
                                                </label>
                                                </li>
                                            
                                            <?php }?>
                                          <!--<li id="user-g">
                                            <input class="enviar_correo" name="userEnviar[]" type="checkbox"> 
                                            <label class="checkbox img-cargar-usuarios">
                                              <img src="http://192.168.1.25:8081/imagenes/usuario/detalle/kevin-8-5242fc4318613.jpg" title="kevin 8">
                                              <a href="/usuario/250">kevin 8</a>
                                              <p>Hello world -.................- !!!!!!!</p>
                                            </label>
                                          </li>-->
 
                                        </ul>
                                        <div class="content-en">
                                          <button type="submit" class="btn btn-warning btn-enviar-correo">Enviar</button>
                                        </div>
                                      </form>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <!--<div id="fb-root"></div>
                              <a href="#" onclick="FB.ui({method: 'apprequests', message: 'Uneté a juntate.pe'});">
                                <span class="face">Invita a tus Amigos de Facebook! </span><img src="/img/invitar.png">
                              </a>-->
                          </div>
                        </div>
                      </div>                      
                    </div>
                  </div>
                   <?php } ?>
                  <div class="mapa-group map-wrapper">
                      <div id="map_canvas"></div>
                  </div>
                  <div class="desc-evento-g">
                      <div id="event-description-wrap" itemprop="description" class="line">
                        <?php echo html_entity_decode($this->eventos[0]['va_descripcion']); ?>
                      </div>
                  </div>
                </div>
                <?php }else{ ?>
                <div class="span12 login-comentario">
                    <p>Evento es privado, unete al grupo para poder visualizarlo.</p>
                </div>
         <?php }} ?>       
         <?php if($this->eventos[0]['va_tipo']=='publico'){ ?>
                 <div class="event-group">
                  <div class="content-img-det">
                      
           <?php  if($this->eventos[0]['va_imagen']=='defaultd.jpg') { ?>           
                      
            <img class="det-img" src="<?php echo $this->host('img')?>/defaultd.jpg" title="Evto macabro" target="Evento macabro">
                <?php } else  {  ?>
            
             <img class="det-img" src="<?php echo $this->host('images') . '/eventos/detalle/' . $this->escapeHtml($this->eventos[0]['va_imagen'])  ?>" title="Evto macabro" target="Evento macabro">
             
<?php } ?>
    <?php if($this->eventos[0]['ta_usuario_in_id']==$session->in_id){?>
                    <div class="content-edit">
                      <a href="/evento/editar/<?php echo $this->idevento?>" title="Editar detalle de evento">
                        <img src="/img/edit.png">
                      </a>
                    </div>
                    <?php } ?>
                  </div>
                   <?php $fecha_actual = date("Y-m-d h:m:s"); 
                    if ( $this->eventos[0]['va_fecha'] >= $fecha_actual)
                    {}
                   else{?> <h2 class="event-caducado">EVENTO CADUCADO</h2> <?php } ?> 
                    <div class="review-block">
                      <div class="overall_score">
                        <h1 class="title-ji"><?php echo $this->eventos[0]['va_nombre']; ?></h1>
                        <ul class="score-list">
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Organizador:  
                            </div>
                            <div class="ficha-desc">
                               <?php echo $this->eventos[0]['nombre_user']; ?>
                            </div>
                          </li>
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Fecha y hora:  
                            </div>
                            <div class="ficha-desc">
                              <p><?php $fecha = date_create($this->eventos[0]['va_fecha']); 
                              $arrayMeses = array('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                              'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
                              echo date_format($fecha, "d").' de '. $arrayMeses[date('m')-1].' del '.date_format($fecha, "Y"); ?></p>
                              <em><?php  $fecha = date_create($this->eventos[0]['va_fecha']);
                                    $hora = date_format($fecha, 'H');
                                  if($hora<12)
                                  { echo date_format($fecha, 'h').':'. date_format($fecha, 'i').' AM'; }
                                  else
                                   { echo date_format($fecha, 'h').':'. date_format($fecha, 'i').' PM'; }

                                ?></em>
                            </div>
                          </li>
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Duración:  
                            </div>
                            <div class="ficha-desc">
                             <?php echo $this->eventos[0]['va_duracion']; ?> Horas
                            </div>
                          </li>
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Precio:  
                            </div>
                            <div class="ficha-desc">
                              S/. <?php echo $this->eventos[0]['va_costo']; ?>
                            </div>
                          </li>
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Categoría:  
                            </div>
                            <div class="ficha-desc">
                              <?php echo $this->eventos[0]['nombre_categoria']; ?>  
                            </div>
                          </li>
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Dirección: 
                              <br>
                              <em>
                               referencia:
                               </em>
                            </div>
                           
                            <div class="ficha-desc">
                              <p><?php echo $this->eventos[0]['va_direccion']; ?></p>
                              <em>(<?php echo $this->eventos[0]['va_referencia']; ?>)</em>
                            </div>
                          </li>
                        </ul> <!-- /score-list -->
                      <div class="clear"></div>
                    </div>  <!-- /overall_score -->  
                  </div>
                  <?php if($this->grupoestado=='activo' && $this->privado==true){ ?>
                  <div class="invitar-amigos">
                    <div class="accordion" id="accordion2">
                      <div class="accordion-group">
                        <div class="accordion-heading">
                          <a class="accordion-toggle invitar" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                            Invitar amigos
                            <img src="/img/add.png">
                          </a>
                        </div>
                            <?php if($this->mensaje_correo){?>
                                   <div class="row-fluid">
                                        <div class="alert alert-success alert-margin">
                                          <?php echo $this->mensaje_correo;?>
                                        </div>
                                      </div>
                                    <?php }?>
                        <div id="collapseOne" class="accordion-body collapse">
                          <div class="accordion-inner">
                              <div id="invita-correo">
                                <div class="row-fluid">
                                  <div class="span6">
                                    <form method="post" action="/grupo/evento/invitar" id="form-correo-s">
                                        <input type="hidden" name="idE" value="<?php echo $this->idevento;?>"/>
                                      <h3>Ingresa correos separado por comas</h3>
                                      <em>Ejm: example@gmail.com, ejemplo@gmail.com</em>
                                      <input type="text" name="correos" class="inputModif"/>
                                      <input type="submit" class="btn btnCorreoForm" name="Enviar"/>
                                    </form>
                                  </div>
                                  <div class="span6">
                                    <div class="span12 user-back-2 email-user-d">
                                      <form method="post" action="/grupo/evento/invitar" id="gruposInvitar">
                                          <input type="hidden" name="idE" value="<?php echo $this->idevento;?>"/>
                                        <h3>Elige a todo tus amigos para enviarles correo de invitación al evento.</h3>
                                        <ul>
                                             <?php foreach($this->grupoeventusuario as $grupousuario){?>
                                                <li id="user-<?php echo $grupousuario->idusuario;?>">
                                                <input class="enviar_correo" name="userEnviar[]" value="<?php echo $grupousuario->idusuario;?>" type="checkbox"> 
                                                <label class="checkbox img-cargar-usuarios">
                                                  <img src="<?php echo $this->host('images')?>/usuario/perfil/<?php echo $grupousuario->imagen;?>" title="<?php echo $grupousuario->nombre_usuario;?>">
                                                  <a href="/usuario/<?php echo $grupousuario->idusuario;?>"><?php echo $grupousuario->nombre_usuario;?></a> 
                                                  <p><?php echo $grupousuario->descripcion_usuario;?></p>
                                                </label>
                                                </li>
                                            
                                            <?php }?>
                                        </ul>
                                        <div class="content-en">
                                          <button type="submit" class="btn btn-warning btn-enviar-correo">Enviar</button>
                                        </div>
                                      </form>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <!--<div id="fb-root"></div>
                              <a href="#" onclick="FB.ui({method: 'apprequests', message: 'Uneté a juntate.pe'});">
                                <span class="face">Invita a tus Amigos de Facebook! </span><img src="/img/invitar.png">
                              </a>-->
                          </div>
                        </div>
                      </div>                      
                    </div>
                  </div>
                   <?php } ?>
                  <div class="mapa-group map-wrapper">
                      <div id="map_canvas"></div>
                  </div>
                  <div class="desc-evento-g">
                      <div id="event-description-wrap" itemprop="description" class="line">
                        <?php echo html_entity_decode($this->eventos[0]['va_descripcion']); ?>
                      </div>
                  </div>
                </div>
         <?php } ?>      
                <div class="event-comentario">

<!-- FORMULARIO COMENTARIO-->
<div class="row-fluid">
    <?php if ($this->session && $this->grupoestado=='activo' && $this->privado==true) { ?>        
        <?php
        $fecha_actual = date("Y-m-d h:m:s");
        if ($this->eventos[0]['va_fecha'] >= $fecha_actual) {
            ?> 
            <div class="span12 comentar-form">
                <h4><?php echo ucwords($this->session->va_nombre); ?>, ¡Comente aquí!</h4>
                <?php
                $form = $this->comentarioform;

                $form->setAttributes(array(
                    'action' => $this->url.'/evento/'.$this->idevento,
                    'method' => 'post',
                    'id' => 'form-comente'
                ));

                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                <div class="row-fluid fn-form">
                    <div class="span2">
                  <?php $valor = explode('/',$this->session->va_foto);
                                    if($valor[0]=='https:'){ ?>  
                                        <img src="<?php echo $this->session->va_foto ;?>?width=80&height=75">                                            
                                    <?php } else {
                                        if(($this->session->va_foto)!="foto-carnet.jpg"){?>
                                            <img src="<?php echo $this->host('images') ?>/usuario/comentarios/<?php echo $this->session->va_foto ;?>" >
                                        <?php }else{?>
                                            <img src="<?php echo $this->host('img') ?>/foto-carnet.jpg">
                                        <?php } 
                                    }?>  
                    </div>
                    <div class="span10">
                      <?php echo $this->formRow($form->get('va_descripcion')); ?>
                    </div>
                    <p class="img-loader-coment">
                      <?php echo $this->formSubmit($form->get('submit')); ?>
                    </p>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
                
                <?php } ?>   
 
        <?php } elseif (!$this->grupocomprueba) { ?>
                <div class="span12 login-comentario">
                    <p>Debes de unirte al evento para comentar.</p>
                </div>

        <?php }elseif($this->grupocomprueba=='desactivo'){?> 
             <div class="span12 login-comentario">
                    <p>Debes de unirte al evento para comentar.</p>
                </div>
        <?php }else { ?>
                <div class="span12 login-comentario">
                    <p><a href="#inline_evento" class="inlineEventoDet">Iniciar session</a> para comentar.</p>
                </div>
        <?php } ?>
        </div>

<?php if($this->privado){ ?>
                  <div class="row-fluid cometarios-detalle">    
                    <h3>Todos los comentarios</h3>
                    <!--  LISTADO COMENTARIOS-->
                    <ul>
                        <?php  foreach ($this->comentarios  as $comentarios) :?>
                      <li> 
                        <div class="content-comentario">
                          <div class="span2">
                       <?php $valor = explode('/',$comentarios->imagen);
                                    if($valor[0]=='https:'){ ?>  
                                        <img src="<?php echo $comentarios->imagen;?>?width=80&height=75">                                            
                                    <?php } else {
                                        if(($comentarios->imagen)!="foto-carnet.jpg"){?>
                                            <img src="<?php echo $this->host('images') ?>/usuario/comentarios/<?php echo $comentarios->imagen;?>" >
                                        <?php }else{?>
                                            <img src="<?php echo $this->host('img') ?>/foto-carnet.jpg">
                                        <?php } 
                                    }?>
                          </div>
                          <div class="span10 ti-coment">
                            <h4><a href="/usuario/<?php echo $comentarios->ta_usuario_in_id;?>"><?php echo  $this->escapeHtml($comentarios->nombre_usuario);?></a></h4>
                            <p><?php echo  $this->escapeHtml($comentarios->va_descripcion);?></p>
                            <p class="small muted">
                             <?php  $fecha = date_create($this->escapeHtml($comentarios->va_fecha));
                                         $arrayMeses = array('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
                echo date_format($fecha, "d").' de '. $arrayMeses[date('m')-1].' del '.date_format($fecha, "Y"); ?>
                            </p>
                          </div>
                        </div>
                      </li>
                       <?php endforeach;  ?>
                    </ul>
              </div>
            <?php } ?>
          </div>
            </div>
            <div class="span3 group-sidebar grupo-right-sidebar">
              <?php if($this->eventos[0]['ta_usuario_in_id']!=$session->in_id){ ?>
              <div class="asistir-event">
                    <?php $fecha_actual = date("Y-m-d h:m:s"); 
                      if ($this->eventos[0]['va_fecha'] >= $fecha_actual)
                    {?>
                    <!--<div class="row-fluid title-side">
                      <h4>¿Asistirás?</h4>
                    </div>-->
                      <?php if ($this->eventos[0]['ta_usuario_in_id'] != $session->in_id) { ?>
                          <?php if ($session) { ?>
                              <?php if ($this->grupoestado == 'activo') { ?>
                                  <?php if ($participa) { ?>
                                    <div class="row-fluid">
                                      <div class="span12 unete-grupo"> 
                                        <a href="#" class="btn btn-danger uneteAbEvent" id="uneteAbEvent">Abandona el evento</a>                                        
                                      </div>
                                    </div>
                                  <?php } else { ?>
                                    <div class="row-fluid">
                                      <div class="span12 unete-grupo">                                        
                                        <a href="#" class="btn btn-success uneteEvent" id="uneteEvent">Unete al evento</a>
                                      </div>
                                    </div>
                                  <?php } ?>
                              <?php } elseif ($this->grupoestado == 'pendiente') { ?>
                                <div class="row-fluid pendiente-revicion">
                                  <div class="span12 unete-grupo">
                                    <p>TU SOLICITUD DE GRUPO ESTA EN ESTADO</p>
                                    <span class="btn btn-warning disabled" id="uneteEvent">Pendiente</span>
                                  </div>      
                                </div>                                
                              <?php } else { ?>
                                <div class="row-fluid evento-desactivo">
                                  <div class="span12 unete-grupo">
                                    <a href="#" class="btn btn-success uneteGrupo" id="uneteGrupo">¡Unete a nosotros!</a> 
                                  </div>
                                </div>
                              <?php } ?>
                          <?php } else { ?>
                          <div class="row-fluid">
                            <div class="span12 unete-grupo">
                            <a href="#inline_evento" class="btn btn-success inlineEvento">Unete al evento</a>
                            </div>
                          </div> 
                        <?php }
                      }?>
                    <?php }?>
              </div>
              <?php } ?>
              <div class="lista-usuario">
                  <ul>
                    <?php if($this->grupoestado=='activo'){ ?>
                      <?php  foreach ($this->usuarios  as $usuarios) :?>
                      <li id="user-<?php echo $usuarios->id_usuario; ?>">
                       <div class="users">
                        <div class="row-fluid">
                            <div class="span4 img-user-ev">
                              <?php $valor = explode('/',$usuarios->imagen); if($valor[0]=='https:'){ ?>  
                                <img src="<?php echo $usuarios->imagen ;?>?width=73&height=68" >                                            
                              <?php } else {if(($usuarios->imagen)!="foto-carnet.jpg"){?>
                                <img src="<?php echo $this->host('images') ?>/usuario/detalle/<?php echo $usuarios->imagen ;?>" >
                              <?php }else{?>
                                <img src="<?php echo $this->host('img') ?>/foto-carnet.jpg">
                              <?php }  }?>  
                            </div>
                            <div class="span8 desc-user">
                                <a href="/usuario/<?php echo $usuarios->id_usuario;?>"><h3><?php echo  $this->escapeHtml($usuarios->nombre_usuario);?></h3></a>
                             <?php if($usuarios->descripcion_usuario)  { ?>
                                <p><?php echo  $this->escapeHtml($usuarios->descripcion_usuario);?></p>
                                <?php } ?>
                            </div>
                        </div>
                        <div class="row-fluid unio">
                           <p class="span12">Se unió el <?php $fecha = date_create($usuarios->va_fecha); 
                              $arrayMeses = array('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                              'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
                              echo date_format($fecha, "d").' de '. $arrayMeses[date('m')-1].' del '.date_format($fecha, "Y"); ?>
                           </p>
                        </div>
                     </div>
                   </li>
                          <?php endforeach;  ?>
                <?php }  ?>
                  </ul>
               </div>
            </div>
        </div>
    </div>
</div> <!-- #main-container -->
<?php }else{ ?>
<div class="main-container">
<div class="span12 login-comentario">
    <p>Evento es privado, unete al grupo para poder visualizarlo.</p>
</div>
    
</div>
<?php } ?>
<script type="text/javascript">
    
  var hostUrl = '<?php echo $this->host("images")?>/usuario/detalle/';

  $(document).on('ready', function(){ 
    enviarDatos();
    abandonarDatos();
    agregarComentario();
    enviarGrupo();

    $('#form-correo-s').validate({
      rules: {
        correos: {
          required: true          
        }
      },
      messages: {
        correos: {
          required: "Ingrese correo electronico"          
        }
        
      }
    });
    $('#gruposInvitar').validate({
      rules: {
        'userEnviar[]': {
          required: true
        }
      },
      messages: {
        'userEnviar[]': {
          required: "Selecciona un usuario"
        }
      }
    });

    $(".btnCorreoForm").click(function(event){
      
    });

  });

  function enviarDatos(){
    var even = <?php echo $this->idevento; ?>;
    $(".uneteEvent").on('click', function(e){
      e.preventDefault();    
      var addLoading = '<img class="img-lo" src="/img/cargando.gif" />';
      $(".unete-grupo").empty();
      $(".unete-grupo").append(addLoading);
      var activo = 1;
      $.ajax({
        url: '/grupo/evento/unir',
        type: 'get',
        data: 'act=' + activo +'&idE='+even,
        dataType: "json",
        success: function(data){
          $(".unete-grupo").remove();
          var elemetoAbandonar = '<div class="row-fluid"><div class="span12 unete-grupo"><a href="#" class="btn btn-danger uneteAbEvent" id="uneteAbEvent">Abandona el evento</a></div></div>';
          $(".asistir-event").prepend(elemetoAbandonar);
          var dataPer = '<li id="user-'+data.userestado["id"]+'">'+
            '<div class="users">'+
                '<div class="row-fluid">'+
                  '<div class="span4 img-user-ev">'+
                    '<img src="'+hostUrl+data.userestado["imagen"]+'" alt="">'+
                  '</div>'+
                  '<div class="span8 desc-user">'+
                    '<h3>'+data.userestado["nombre_usuario"]+'</h3>'+
                    '<p>'+data.userestado["descripcion_usuario"]+'</p>'+
                  '</div>'+
                '</div>'+
                '<div class="row-fluid unio">'+
                  '<p class="span12">'+data.userestado["va_fecha"]+'</p>'+
                '</div>'+
            '</div>'+
            '</li>';
          $(".lista-usuario ul").prepend(dataPer);
          abandonarDatos();
          $("#comentarioR").load("/grupo/evento/comentarios", '', function(){
            alert("recibidos los datos por ajax");
          });
        },
        error: function(){
            console.log('Fallo conectando con el servidor')
        }
      });
    });

  }

  function abandonarDatos(){
    var even = <?php echo $this->idevento; ?>;
    $(".uneteAbEvent").on('click', function(e){
      e.preventDefault();    
      var addLoading = '<img class="img-lo" src="/img/cargando.gif" />';
      $(".unete-grupo").empty();
      $(".unete-grupo").append(addLoading);
      var activo = 0;
      $.ajax({
        url: '/grupo/evento/unir',
        type: 'get',
        data: 'act=' + activo +'&idE='+even,
        dataType: "json",
        success: function(data){
          var datoId = data.userestado["id"];          
          $(".unete-grupo").remove();
          var addbtnAdd = '<div class="row-fluid"><div class="span12 unete-grupo"><a href="#" class="btn btn-success uneteEvent" id="uneteEvent">Unete al evento</a></div></div>';
          $(".asistir-event").prepend(addbtnAdd);
          $(".lista-usuario ul li#user-"+datoId).remove();
          enviarDatos();
        },
        error: function(){
          console.log('Fallo conectando con el servidor')
        }
      });
    });
  }

  function agregarComentario(){
    $(".btn-enviar-mensaje").click(function(e){
      e.preventDefault();
      var addLoadingCom = '<img class="img-lo" src="/img/cargando.gif" />';
      $(".img-loader-coment").prepend(addLoadingCom);
      var coment = $("#texto-comentar").val();
      var idEventoC = <?php echo $this->idevento; ?>; 
      var data_obj = { 
        'in_id' : idEventoC,
        'va_descripcion' : coment
      }

      $.ajax({
        url: '/grupo/evento/comentarios',
        type: 'post',
        data: data_obj,
        dataType: "json",
        success: function(data){
          //var datoId = data.userestado["id"];
          var comentarioF = '<li>'+
                              '<div class="content-comentario">'+
                                '<div class="span2">'+
                                  '<img src="'+hostUrl+data.userestado["imagen"]+'" alt="">'+
                                '</div>'+
                                '<div class="span10 ti-coment">'+
                                  '<h4><a href="#">'+data.userestado["nombre_usuario"]+'</a></h4>'+
                                  '<p>'+data.descripcion["va_descripcion"]+'</p>'+
                                  '<p class="small muted">'+data.userestado["va_fecha"]+'</p>'+
                                '</div>'+
                              '</div>'+
                            '</li>';
          $(".cometarios-detalle ul").prepend(comentarioF);
          $('#texto-comentar').val('');
          $(".img-lo").hide();
        },
        error: function(){
          console.log('Fallo conectando con el servidor')
        }
      });
    });
  }

  function enviarGrupo(){
        var even = <?php echo $this->idevento; ?>;
        $(".uneteGrupo").on('click', function(e){
            e.preventDefault();
            var addLoading = '<img class="img-lo" src="/img/cargando.gif" />';
            $(".unete-grupo").empty();
            $(".unete-grupo").append(addLoading);
            var activo = 1;
            $.ajax({
                url: '/grupo/evento/unir',
                type: 'get',
                data: 'act=' + activo +'&idE='+even,
                dataType: "json",
                success: function(data){
                    $(".img-lo").hide();   
                    $(".evento-desactivo").remove();
                    $(".grupo-right-sidebar").append('<div class="row-fluid pendiente-revicion"><div class="span12 unete-grupo"><p>TU SOLICITUD DE GRUPO ESTA EN ESTADO</p><span class="btn btn-warning disabled" id="uneteEvent">Pendiente</span></div></div>');
                    //$(".unete-grupo .uneteEvent").remove();
                    clickUnir();
                },
                error: function(){
                    console.log('Fallo conectando con el servidor')
                }
            });
        });
        
    }

</script>