<div class="main-container">
    <div class="container">
       <?php if ($this->mensajes) { ?>
                <div class="row-fluid">
                    <div class="alert alert-success alert-margin">
                        <?php
                        foreach ($this->mensajes as $message) {
                            echo $message;
                        }
                        ?>
                    </div>
                </div>
<?php } ?>
        <div class="row-fluid">
            <div class="span3 group-sidebar">
              <div class="img-grupo">
                <a href="/grupo/index/detallegrupo/<?php echo $this->escapeHtml($this->eventos[0]['id_grupo'], ENT_QUOTES, 'utf-8');  ?>">
                  <img src="<?php echo $this->host('images') . '/grupos/general/' . htmlspecialchars($this->eventos[0]['imagen'], ENT_QUOTES, 'utf-8');  ?>">
                </a>
              </div>
             
              <h2 class="gh"><a href="/grupo/index/detallegrupo/<?php echo $this->escapeHtml($this->eventos[0]['id_grupo'], ENT_QUOTES, 'utf-8');  ?>"><?php echo $this->eventos[0]['nombre_grupo']; ?>  </a></h2>
              <p class="fund gh">
                <em>Fundado el <?php $fecha = date_create($this->eventos[0]['fecha_creacion']); 
                $arrayMeses = array('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
                echo date_format($fecha, "d").' de '. $arrayMeses[date('m')-1].' del '.date_format($fecha, "Y"); ?></em>
              </p>
              <p class="desc gh">
                <?php echo $this->eventos[0]['descripcion']; ?> <br> <a href="#">Ver mas...</a>
              </p>
              <p class="gh ft"><a class="dp" href="#"><span class="cant-user ab">Nº Usuarios</span> <span class="nm"><?php echo $this->grupo[0]['cantidad']; ?></span></a></p>
              <p class="gh ft"><a class="dp" href="#"><span class="cant-evento-f ab">Evento futuros</span> <span class="nm"><?php echo $this->eventosfuturos[0]['eventosfuturos']; ?></span></a></p>
              <p class="gh ft">
                <a class="dp" href="#">
                  <span class="cant-evento-p ab">Evento pasados</span> 
                  <span class="nm"><?php echo $this->eventospasados[0]['eventospasados']; ?></span>
                </a>
              </p>
              <!--<h3 class="title-si">Organizador</h3>
              <ul>
                <li><a href="#">Jesser pariona</a></li>
              </ul>-->
            </div>
            <div class="span6 group-sidebar">
                <div class="event-group">
                  <div class="content-img-det">
                    <img src="<?php echo $this->host('images') . '/eventos/detalle/' . $this->escapeHtml($this->eventos[0]['va_imagen'])  ?>" title="Evto macabro" target="Evento macabro">
                    <?php if($this->eventos[0]['ta_usuario_in_id']==$session->in_id){?>
                    <div class="content-edit">
                      <a href="/evento/editar/<?php echo $this->idevento?>" title="Editar detalle de evento">
                        <img src="/img/edit.png">
                      </a>
                    </div>
                    <?php } ?>
                  </div>
                   <?php $fecha_actual = date("Y-m-d h:m:s"); 
                    if ( $this->eventos[0]['va_fecha'] >= $fecha_actual)
                    {}
                   else{?> <h2>EVENTO CADUCADO</h2> <?php } ?> 
                    <div class="review-block">
                      <div class="overall_score">
                        <h1><?php echo $this->eventos[0]['va_nombre']; ?></h1>
                        <ul class="score-list">
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Organizador:  
                            </div>
                            <div class="ficha-desc">
                               <?php echo $this->eventos[0]['nombre_user']; ?>
                            </div>
                          </li>
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Fecha y hora:  
                            </div>
                            <div class="ficha-desc">
                              <p><?php $fecha = date_create($this->eventos[0]['va_fecha']); 
                $arrayMeses = array('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
                echo date_format($fecha, "d").' de '. $arrayMeses[date('m')-1].' del '.date_format($fecha, "Y"); ?></p>
                              <em><?php  $fecha = date_create($this->eventos[0]['va_fecha']);
                                    $hora = date_format($fecha, 'h');
                                            if($hora<12)
                                            { echo $hora.':'. date_format($fecha, 'm').' AM'; }
                                            else
                                             { echo $hora.':'. date_format($fecha, 'm').' PM'; }
                                   ?></em>
                            </div>
                          </li>
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Duración:  
                            </div>
                            <div class="ficha-desc">
                             <?php echo $this->eventos[0]['va_duracion']; ?> Horas
                            </div>
                          </li>
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Precio:  
                            </div>
                            <div class="ficha-desc">
                              S/. <?php echo $this->eventos[0]['va_costo']; ?>
                            </div>
                          </li>
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Categoría:  
                            </div>
                            <div class="ficha-desc">
                              <?php echo $this->eventos[0]['nombre_categoria']; ?>  
                            </div>
                          </li>
                          <li class="clearfix">
                            <div class="ficha-dep">
                              Dirección: 
                              <br>
                              <em>
                               referencia:
                               </em>
                            </div>
                           
                            <div class="ficha-desc">
                              <p><?php echo $this->eventos[0]['va_direccion']; ?></p>
                              <em>(<?php echo $this->eventos[0]['va_referencia']; ?>)</em>
                            </div>
                          </li>
                        </ul> <!-- /score-list -->
                      <div class="clear"></div>
                    </div>  <!-- /overall_score -->  
                  </div>


                    <div class="mapa-group map-wrapper">
                        <div id="map_canvas"></div>
                    </div>
                    <div class="desc-evento-g">
                        <div id="event-description-wrap" itemprop="description" class="line">
                            <p><?php echo html_entity_decode($this->eventos[0]['va_descripcion']); ?></p>
                        </div>
                    </div>
                </div>
                <div class="event-comentario">
                  <div class="row-fluid">
                  <?php if($this->session && $this->grupocomprueba){?>
                      
                   <?php $fecha_actual = date("Y-m-d h:m:s"); 
                    if ( $this->eventos[0]['va_fecha'] >= $fecha_actual)
                    {?> 
                    <div class="span12 comentar-form">
                      <h4><?php echo ucwords($this->session->va_nombre);?>, ¡Comente aqui!</h4>
                <?php
                    $form = $this->comentarioform;
            
                    $form->setAttributes(array(
                        'action' => $this->url.'/evento/'.$this->idevento,
                        'method' => 'post',
                        'id'=>'form-comente'
                    ));
            
                    $form->prepare();
                    echo $this->form()->openTag($form);
                 ?>
                        <div class="row-fluid fn-form">
                          <div class="span2">
                            <img src="../../img/foto-carnet.jpg" alt="">
                          </div>
                          <div class="span10">
                          <?php echo $this->formRow($form->get('va_descripcion'));?>
                          </div>
                          <p>
                          <?php echo $this->formSubmit($form->get('submit'));?>
                          </p>
                        </div>
                            <?php echo $this->form()->closeTag();?>
                    </div>
                      
                      <?php  } else {}?>
                      
                      
                      
                      
                     <?php }elseif(!$this->grupocomprueba){?>
                     <div class="span12 login-comentario">
                      <p>Debes de unirte al evento para comentar.</p>
                    </div>
                     
                    <?php }else{?>
                    <div class="span12 login-comentario">
                      <p><a href="#inline_evento" class="inlineEventoDet">Iniciar session</a> para comentar.</p>
                    </div>
                    <?php }?>
                  </div>
                  <div class="row-fluid cometarios-detalle">
                    <ul>
                        <?php  foreach ($this->comentarios  as $comentarios) :?>
                      <li> 
                        <div class="content-comentario">
                          <div class="span2">
                       <?php if(($comentarios->imagen)!="foto-carnet.jpg"){?>
                     <img src="<?php echo $this->host('images') ?>/usuario/comentarios/<?php echo $comentarios->imagen ;?>" alt="">
                     <?php }else{?>
                      <img src="<?php echo $this->host('img') ?>/foto-carnet.jpg" alt="">
                      <?php }?>
                          </div>
                          <div class="span10 ti-coment">
                            <h4><a href="#"><?php echo  $this->escapeHtml($comentarios->nombre_usuario);?></a></h4>
                            <p><?php echo  $this->escapeHtml($comentarios->va_descripcion);?></p>
                            <p class="small muted">
                             <?php  $fecha = date_create($this->escapeHtml($comentarios->va_fecha));
                                         $arrayMeses = array('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
                echo date_format($fecha, "d").' de '. $arrayMeses[date('m')-1].' del '.date_format($fecha, "Y"); ?>
                            </p>
                          </div>
                        </div>
                      </li>
                       <?php endforeach;  ?>
                    </ul>
                  </div>
                </div>
            </div>
            <div class="span3 group-sidebar grupo-right-sidebar">
              <div class="asistir-event">
                <div class="row-fluid">
                  <div class="span12">
                     <?php $fecha_actual = date("Y-m-d h:m:s"); 
                    if ( $this->eventos[0]['va_fecha'] >= $fecha_actual)
                    {?>   
                    <div class="row-fluid title-side">
                      <h4>¿Asistiras?</h4>
                    </div>
                    <div class="row-fluid">
                      <div class="span12 btn-unete">
                      <?php if($this->eventos[0]['ta_usuario_in_id']!=$session->in_id){ ?>
                        <?php if($session){?>
                            <?php if($participa){?>
                            <a href="#" class="btn btn-danger uneteAbEvent" id="uneteAbEvent">Abandona el evento</a>
                            <a href="#" class="btn btn-success uneteEvent" id="uneteEvent" style="display:none;">Unete al evento</a>
                            <?php }else{?>
                            <a href="#" class="btn btn-success uneteEvent" id="uneteEvent">Unete al evento</a>
                            <a href="#" class="btn btn-danger uneteAbEvent" id="uneteAbEvent" style="display:none;">Abandona el evento</a>
                            <?php }?>
                          <?php }else{?>
                            <a href="#inline_evento" class="btn btn-success inlineEvento">Unete al evento</a> 
                          <?php }}?>                   
                      </div>
                    </div> <?php }
                   else { } ?>  
                  </div>     
                </div>
               </div>
               <div class="lista-usuario">
                  <ul>
                    <li>
                      <div class="users">
                         <?php  foreach ($this->usuarios  as $usuarios) :?>
                        <div class="row-fluid">
                            <div class="span4 img-user-ev">
                  
                              <?php if(($usuarios->imagen)!="foto-carnet.jpg"){?>
                     <img src="<?php echo $this->host('images') ?>/usuario/detalle/<?php echo $usuarios->imagen ;?>" alt="">
                     <?php }else{?>
                      <img src="<?php echo $this->host('img') ?>/foto-carnet.jpg" alt="">
                      <?php }?>
                            </div>
                            <div class="span8 desc-user">
                                <h3><a href="#"><?php echo  $this->escapeHtml($usuarios->nombre_usuario);?></a></h3>
                               <p><?php echo  $this->escapeHtml($usuarios->descripcion_usuario);?></p>
                            </div>
                        </div>
                        <div class="row-fluid unio">
                           <p class="span12">Se unio el <?php  $fecha = date_create($this->escapeHtml($usuarios->va_fecha));
                                         echo $fecha = date_format($fecha, "d \d\e\l m \d\e\l Y"); ?></p>
                        </div>
                          <?php endforeach;  ?>
                      </div>
                    </li>
                  </ul>
               </div>
            </div>
        </div>
    </div>
</div> <!-- #main-container -->

<script type="text/javascript">
  
  $(document).on('ready', function(){   
    enviarDatos();
    abandonarDatos();
  });

  function enviarDatos(){
    var even = <?php echo $this->idevento; ?>;
    $(".uneteEvent").on('click', function(e){
      e.preventDefault();    
      var addLoading = '<img class="img-lo" src="/img/cargando.gif" />';
      $(".btn-unete").append(addLoading);
      $(".uneteEvent").hide();
      $(".uneteAbEvent").hide();
      var activo = 1;
      $.ajax({
        url: '/grupo/evento/unir',
        type: 'get',
        data: 'act=' + activo +'&idE='+even,
        dataType: "json",
        success: function(data){
          $(".img-lo").hide();
          $(".uneteAbEvent").show();
          var dataPer = '<li>'+
            '<div class="users">'+
                '<div class="row-fluid">'+
                  '<div class="span4 img-user-ev">'+
                    '<img src="'+data.userestado["imagen"]+'" alt="">'+
                  '</div>'+
                  '<div class="span8 desc-user">'+
                    '<h3><a href="#">'+data.userestado["nombre_usuario"]+'</a></h3>'+
                    '<p>'+data.userestado["descripcion_usuario"]+'</p>'+
                  '</div>'+
                '</div>'+
                '<div class="row-fluid unio">'+
                  '<p class="span12">'+data.userestado["va_fecha"]+'</p>'+
                '</div>'+
            '</div>'+
            '</li>';
          $(".lista-usuario ul").prepend(dataPer);
        },
        error: function(){
            console.log('Fallo conectando con el servidor')
        }
      });
    });

  }

  function abandonarDatos(){
    var even = <?php echo $this->idevento; ?>;
    $(".uneteAbEvent").on('click', function(e){
      e.preventDefault();    
      var addLoading = '<img class="img-lo" src="/img/cargando.gif" />';
      $(".btn-unete").append(addLoading);
      $(".uneteAbEvent").hide();
      $(".uneteEvent").hide();
      var activo = 0;
      $.ajax({
        url: '/grupo/evento/unir',
        type: 'get',
        data: 'act=' + activo +'&idE='+even,
        dataType: "json",
        success: function(data){
          $(".img-lo").hide();
          $(".uneteEvent").show();
          $(".lista-usuario ul li:first-child").remove();
        },
        error: function(){
            console.log('Fallo conectando con el servidor')
        }
      });
    });
  }

</script>