<div class="main-container">
	<div class="container">
		<div class="row-fluid">
			<div class="row-fluid crear-evento-grupos">
            <?php
        $form = $this->formevento;

        $form->setAttributes(array(
            'action' => $this->url.'/grupo/evento/agregarevento/'.$this->in_id,
            'method' => 'post',
            'class'=>'span12 form-crear-grupo',
            'id'=>'crearEventos'
        ));

        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
    <?php echo $this->formHidden($form->get('in_id'));?>
    <?php echo $this->formHidden($form->get('ta_usuario_in_id'));?>

        <div class="row-fluid">
					<div class="span12 crear-evento event">
						<h1>Crear un nuevo evento</h1>
						<p>¡Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed
							diam nonummy!</p>
					</div>
				</div>
				<div class="row-fluid crear-evento-1 event">
					<h2>Describe tu evento</h2>
					<div class="span8 desc-evento">
                <?php echo $this->formRow($form->get('va_nombre'));?>
                <label>Descripción del evento:</label>
                <?php echo $this->formRow($form->get('va_descripcion'));?>
                <!--<textarea class="ckeditor" cols="80" id="editor1" name="editor1" rows="10"></textarea>-->
					</div>
					<div class="span4">
						<div class="control-group">
							<label for="textfield" class="control-label"></label>
							<div class="controls">
								<div class="fileupload fileupload-new"
									data-provides="fileupload">
									<div class="fileupload-new thumbnail"
										style="width: 200px; height: 150px;">
										<img
											src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" />
									</div>
									<div class="fileupload-preview fileupload-exists thumbnail"
										style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
									<div>
										<span class="btn btn-file"><span class="fileupload-new">Selecione
												una imagen</span><span class="fileupload-exists">Cambiar</span>
                                   <?php echo $this->formRow($form->get('va_imagen'));?>
                                </span> <a href="#"
											class="btn fileupload-exists" data-dismiss="fileupload">Eliminar</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row-fluid crear-evento-2 event">
					<h2>Cuando? y Cuanto sera el precio.</h2>
					<div class="span3 fecha event-padding">
						<div class="form_row">
							<label class="field_name">Fecha y hora:</label>
							<div class="field">
                    <?php 
//                     use Zend\Form\Form;
//                     use Zend\Form\Element;
//                     $textElement     = new Element\Text('va_fecha');
//                     $textElement->setAttributes(array(
//                         'size'=>16,
//                         'readonly' => 'true',
//                         'class' => 'span10',
//                         'id'=>'fechaId'
//                     ));
//                     ?>
                        <div
									class="span10 input-append date form_datetime2"
									data-date="<?php echo $form->get('va_fecha')->getValue();?>">
                            <?php echo $this->formRow($form->get('va_fecha'));
//                             $this->formElement($textElement);
                            ?>
                            <span class="add-on"><i class="icon-remove"></i></span>
									<span class="add-on"><i class="icon-calendar"></i></span>
								</div>
							</div>
						</div>
					</div>
					<div class="span3">
						<label class="field_name">Duración del evento:</label>
						<div class="input-prepend input-append">
							<span class="add-on"><i class="icon-time"></i></span>
                    <?php echo $this->formRow($form->get('va_duracion'));?>
                    <span class="add-on">Horas</span>
						</div>
					</div>
					<div class="span3">
						<label class="field_name">Precio referencial para el evento:</label>
						<div class="input-prepend input-append">
							<span class="add-on">S/.</span>
                     <?php echo $this->formRow($form->get('va_costo'));?>
                    <span class="add-on">.00</span>
						</div>
					</div>
					<div class="span3">
						<div class="control-group span5">
							<label class="control-label" for="inputIcon">Minimo:</label>
							<div class="controls">
								<div class="input-prepend">
									<span class="add-on"><i class="icon-user"></i></span>
                      <?php echo $this->formRow($form->get('va_min'));?>
                    </div>
							</div>
						</div>
						<div class="control-group span5">
							<label class="control-label" for="inputIcon">Maximo:</label>
							<div class="controls">
								<div class="input-prepend">
									<span class="add-on"><i class="icon-user"></i></span>
                      <?php echo $this->formRow($form->get('va_max'));?>
                    </div>
							</div>
						</div>
					</div>
				</div>
				<div class="row-fluid crear-evento-3 event">
					<h2>Elige el lugar del evento</h2>
					<div class="span12 event-padding dev-padd">
						<label>Address : </label> <input id="addresspicker_map" />
						<div id="map" class="span12 event-padding height-evento" style="border: 1px solid #eee;"></div>
					</div>
					<div class="span3 lugar-nm event-padding">
						<div class="form-item">
							<div id="cityId-label" class="item-label">
								<label for="cityId" class="required">Ciudad</label>
							</div>
							<div class="item-value">
                        <?php echo $this->formRow($form->get('ta_ubigeo_in_id'));?>
                    </div>
						</div>
					</div>
					<div class="span5">
						<div class="form-item tooltip-errors">
							<div id="address-label" class="item-label">
								<label for="address" class="required">Dirección</label>
							</div>
							<div class="item-value">

                        <?php echo $this->formRow($form->get('va_direccion'));?>
                    </div>
						</div>
					</div>
					<div class="span3">
						<div class="form-item tooltip-errors">
							<div id="addressReference-label" class="item-label">
								<label for="addressReference" class="optional">Referencia de
									ubicación</label>
							</div>
							<div class="item-value">
                         <?php echo $this->formRow($form->get('va_referencia'));?>                      
                    </div>
						</div>
                <?php echo $this->formRow($form->get('va_latitud'));?>
                <?php echo $this->formRow($form->get('va_longitud'));?>       
            </div>
				</div>
				<p class="crear-evento">
            <?php echo $this->formSubmit($form->get('submit'));?>
        </p>
            <?php echo $this->form()->closeTag();?>
    </div>

		</div>
	</div>
</div>
<script>
    $(document).ready(function(){
        
    $('#submitbutton').click(function (){
        
   	 var a=$('#address').val();
   	 var b=$('#fechaId').val();
    	alert(a);
    	alert(b);
        });});
                   
                    
 </script>