<div class="main-container">
    <div class="container">
    	<div class="row-fluid">
        	<div class="span12 contenido-group">
        		<div class="row-fluid">
        			<?php echo $this->grupo; ?>
        		</div>
        		<div class="row-fluid mi-grupo">
        			<header class="span12"><span>Mis Eventos</span> <div class="agrupos"><a href="crear-evento.html">Crear nuevo evento</a></div></header>
        		</div>
				<div class="row-fluid">
					<div class="span12 main wrapper" id="content" data-ui-scrollbar>
	                    <ul>
	                       <?php  foreach ($this->miseventos  as $miseventos) :?>
	                        <li data-category="web">
	                            <a href="/grupo/evento/detalleevento?id=<?php echo $this->escapeHtml($miseventos->in_id); ?>" class="preview" data-ui-lightbox>
	                                <img src="<?php   echo $this->host('images') . '/eventos/general/' . htmlspecialchars($miseventos->va_imagen, ENT_QUOTES, 'utf-8');  ?>" alt=""/>
	                            </a>
	                            <div class="content">
	                                <div class="info">
	                                    <span><?php  $fecha = date_create($miseventos->va_fecha);
                                         echo $fecha = date_format($fecha, 'd/m/Y'); ?></span>
	                                    <span class="category"><a href="#"><?php echo  $this->escapeHtml($miseventos->nombre_categoria);?></a></span>
	                                </div>
	                                <h2><a href="/grupo/evento/detalleevento?id=<?php echo $this->escapeHtml($miseventos->in_id); ?>"><?php echo  $this->escapeHtml($miseventos->va_nombre);?></a></h2>
	                                <p>
	                               <?php echo  $this->escapeHtml($miseventos->va_descripcion);?>
	                                </p>
	                            </div>
	                        </li>
	                         <?php endforeach;  ?>
	                       

	                    </ul>               
	                </div> 
				</div>
             <!--   <div class="row-fluid">
                	<header class="span12"><span>Grupos Similares</span></header>
                </div>
				<div class="row-fluid">
					<div class="span12 main wrapper" id="content" data-ui-scrollbar>
		                <ul>
		                   
		                    <li data-category="web">
		                        <a href="#" class="preview" data-ui-lightbox>
		                            <img src="../../img/eventos/1.jpg" alt=""/>
		                        </a>
		                        <div class="content">
		                            <div class="info">
		                                <span>2013</span>
		                                <span class="category"><a href="#">Web</a></span>
		                            </div>
		                            <h2><a href="#">Tumidei Spa</a></h2>
		                            <p>
		                                Corporate web site. Html5. Responsive.
		                            </p>
		                        </div>
		                    </li>
		              
		                    <li data-category="art">
		                        <a href="#" class="preview" data-ui-lightbox>
		                            <img src="../../img/eventos/2.jpg" alt=""/>
		                        </a>
		                        <div class="content">
		                            <div class="info">
		                                <span>2013</span>
		                                <span class="category"><a href="#">Art</a></span>
		                            </div>
		                            <h2><a href="#">Crazy Home</a></h2>
		                            <p>
		                                Overdrive realizza Art Image (quadri e mobili d'arredo) in collaborazione con Crazy Home.
		                            </p>
		                        </div>
		                    </li>  

		                     
		                    <li data-category="foto">
		                         <a href="#" class="preview" data-ui-lightbox>
		                            <img src="../../img/eventos/3.jpg" alt=""/>
		                        </a>
		                        <div class="content">
		                            <div class="info">
		                                <span>2013</span>
		                                <span class="category"><a href="#">Lo Studio</a></span>
		                            </div>
		                            <h2><a href="#">Overdrive</a></h2>
		                            <p>
		                                I nostro Quartier Generale. Lissone. Piazzale Giotto 1.
		                            </p>
		                        </div>
		                    </li> 
		            	</ul>               
		    		</div>
				</div> -->
	    </div>
    </div>
  </div>
</div>


