		<div class="footer-container">
            <footer class="container">
                <h3>footer</h3>
            </footer>
        </div>
        <!--Script-->

        <script src="/js/main.js"></script>
        <script>
            $(document).ready(function(){
                $(".inlineEvento").colorbox({inline:true, width:"500px"});
            });
        </script>
         <?php echo $this->inlineScript() ?>
        <?php if($this->partial){ ?>
         <script src="<?php echo $this->partial;?>"></script>
        <?php } ?>

    </body>
</html>

