		<div class="footer-container">
            <footer class="container">
                <div class="row-fluid foo1">
                    <div class="span8 terminos-condiciones">
                        <ul>
                            <li><a href="/grupo/index/nosotros">Nosotros</a></li>
                            <li><a href="/grupo/index/terminos">Términos y condiciones</a></li>
                        </ul>
                        <!--<div class="row-fluid">
                            <div class="span3 menus-footer">
                                <h3>TÍTULO SECCIÓN</h3>
                                <ul>
                                    <li><a href="#">Términos y condiciones</a></li>
                                </ul>
                            </div>
                            <div class="span3 menus-footer">
                                &nbsp
                            </div>
                            <div class="span3 menus-footer">
                                &nbsp
                            </div>
                            <div class="span3 menus-footer">
                                &nbsp
                            </div>
                        </div>-->
                    </div>
                    <div class="span4 compar">
                        <span>SÍGUENOS EN</span>
                        <ul>
                            <li>
                                <a href="#"><div class="face-f"></div></a>
                            </li>
                            <li>
                                <a href="#"><div class="twitter-t"></div></a>
                            </li>
                        </ul>
                    </div>
                    <div class="contendor-efecto"></div>
                </div>
            </footer>
        </div>
        <div class="footer2-container">
            <div class="container">
                <p class="left">
                    JUNTATE.PE - Copyright © 2010-2013 
                </p>
                <p class="right">
                    DESARROLLADO POR <a href="#">ISG</a>
                </p>
            </div>
        </div>

        <!--Script-->
        <script src="<?php echo $this->host('base');?>/js/bootstrap.js"></script>
        <script src="<?php echo $this->host('base');?>/js/bootstrap-dropdown.js"></script>
        <script src="<?php echo $this->host('base');?>/js/bootstrap-alert.js"></script>
        <script src="<?php echo $this->host('base');?>/js/bootstrap-button.js"></script>
        <script src="<?php echo $this->host('base');?>/js/bootstrap-collapse.js"></script>
        <script src="<?php echo $this->host('base');?>/js/jquery.colorbox-min.js"></script>
        <!--Home evento-->
        
        <?php echo $this->inlineScript() ?>
        <script>
            jQuery(document).ready(function(){
                jQuery(".inlineEvento").colorbox({inline:true, width:"500px"});
                jQuery("#usuario").submit(function(){
                  
                });
                jQuery(".eventDato").click(function(){
                    jQuery("#origen").val('ingresarPrin');
                });
                jQuery(".btn-home-evnt").click(function(){
                    jQuery("#origen").val('');
                });
                
            });
        </script>
    </body>
</html>

