<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# juntate: http://ogp.me/ns/fb/juntate#">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Juntate.pe</title>
       
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="<?php echo $this->host('ruta')?>/img/favicon.ico" type="image/vnd.microsoft.icon">
        <!--<link rel="stylesheet" href="css/normalize.min.css">-->
        <link rel="stylesheet" href="<?php echo $this->host('ruta')?>/css/bootstrap.css">
        <link rel="stylesheet" href="<?php echo $this->host('ruta')?>/css/bootstrap-responsive.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->host('ruta')?>/css/font-awesome.min.css">
        <link rel="stylesheet" href="<?php echo $this->host('ruta')?>/css/main.css">

        <link rel="stylesheet" href="<?php echo $this->host('ruta')?>/css/masonry.css">
        <link rel="stylesheet" href="<?php echo $this->host('ruta')?>/css/options.css">

        <?php echo $this->headLink(); ?>
        		
        <script src="<?php echo $this->host('ruta')?>/js/modernizr.js"></script>
        <script src="<?php echo $this->host('ruta')?>/js/vendor/jquery.js"></script>
</head>
<body id="blog">
	<div class="navbar navbar-inverse navbar-fixed-top menu-grup">
		<div class="navbar-inner">
			<div class="container">
                <?php if($_GET['nombre']) {?> <span class="category-home">Categoria: <?php echo $_GET['nombre'] ?></span><?php } ?>
                <div class="nav-collapse collapse navbar-responsive-collapse">
					<ul class="nav pull-right menu-dev">
                        <?php if(!$this->session){?>
                        <li class="top-ini"><a href="#inline_evento" class="inlineEvento eventDato">Iniciar sesion</a></li>
						<li class="divider-vertical divider-one"></li>
						<li class="top-ini"><a href="/registrarse">Registrarse</a></li>
                    <?php }else{?>
                    <li class="dropdown">
                      <a href="#" class="buttom dropdown-toggle" data-toggle="dropdown"><?php echo $this->session->va_nombre;?>
                          
                 <?php if($this->session->id_facebook) {?> <img src="<?php echo $this->session->va_foto?>" alt="">
                      <?php } else{  ?><img src="<?php echo $this->host('images').'/usuario/perfil/'.$this->session->va_foto?>" alt=""> <?php } ?>
                      </a>

						<ul class="dropdown-menu">
							<li><a href="<?php echo $this->host('base');?>/micuenta">Mi perfil</a></li>
							<li><a href="<?php echo $this->host('base');?>/cuenta/miseventos">Mis eventos</a></li>
							<li><a href="<?php echo $this->host('base');?>/cuenta/misgrupos">Mis grupos</a></li>
							<li class="divider"></li>
                            <?php // if($this->session->va_logout!=='') 
                            //{?>
                            <!--<li><a href="<?php echo $this->url('login/process', array('action'=>'logout','in_id_face'=>$this->session->va_logout)); ?>">Cerrar sesión N</a></li>-->
                               
                            <?php // }else{?>
                                <li><a href="<?php echo $this->url('login/process', array('action'=>'logout')); ?>">Cerrar sesión N</a></li>
                            <?php // }?>
						</ul>
                    </li>
                    <?php }?>
                    </ul>
				</div>
				<!-- /.nav-collapse -->
			</div>
		</div>
	</div>
	<div class="search">
		<div class="container">
			<div class="row-fluid" style="position:relative;">
				<div class="span9 form-search">
                    <div class="logo-juntate">
                        <a class="brand logo-juntate" href="/" title="juntate.pe">
                            <img src="/img/juntate.png" title="juntate.pe">
                        </a>
                    </div>
                    <div class="contenedor-slogan">
                        <p class="primer">conoce amigos,</p>
                        <p class="segundo"><span>organiza eventos</span> y más!</p>
                    </div>
                    <div class="contenedor-btn-form">
                        <?php if(!$this->session){?>
                        <a href="#inline_evento" class="btn btn-success btn-home-evnt inlineEvento">CREA UN EVENTO</a>
                         <?php }else{?>
                        <a href="<?php echo $this->url('elegir-grupo');?>" class="btn btn-success btn-home-evnt">CREA UN EVENTO</a>
                        <?php }?>
                        <form method="post" class="form-search-dev span8 dropdown" name="search" action="<?php echo $this->host('ruta')?>/grupo/index/index">
                            <input type="text"
                                value="<?php
                                if ($_POST['dato']) {
                                        $filter = new \Zend\I18n\Filter\Alnum(true);
                                        $nombre = trim($filter->filter($_POST['dato']));
                                        echo $nombre;
                                    } else {
                                        echo $_COOKIE['dato'];
                                    }
                                    ?>"
                                name="dato"
                                class="input-medium search-query span10 dropdown-toggle"
                                data-toggle="dropdown" id="search-home" placeholder="INGRESA TU BUSQUEDA">
                                <ul class="dropdown-menu" id="menu-categoria">
                                    <?php
                                    foreach ($this->categorias as $categorias) :
                                        ?>
                                    <li class="man-dev">
                                        <ul>  
                                            <li><a href="<?php echo $this->host('ruta')?>/grupo/index/index?nombre=<?php echo $this->escapeHtml($categorias->va_nombre); ?>&categoria=<?php echo $this->escapeHtml($categorias->in_id); ?>&valor=<?php if($_COOKIE['tipo']){echo $_COOKIE['tipo'];}else {echo $_GET['tipo'];} ;?>"><?php echo $this->escapeHtml($categorias->va_nombre); ?></a></li>
                                        </ul>
                                    </li> 
                                     <?php endforeach; ?>  
                                </ul>
                            <input type="submit"  class="btn btn-primary btn-evento-i" value=""/>
                        </form>
                    </div>
                </div>
                <div class="span3 btn-evento">
                    <div class="btn-group group-right" data-toggle="buttons-radio"> 
                        <a class="btn btn-primary <?php if( $_GET['tipo']=='Eventos' or $_GET['valor']=='Eventos'){echo 'active';}else{} ?> tab-home-g-a" href="<?php echo $this->host('ruta')?>/grupo/index/index?tipo=Eventos">
                            EVENTOS
                            <div class="pinchitoa"></div>
                        </a>
                        <a class="btn btn-primary <?php if($_GET['tipo']=='Grupos' or $_GET['valor']=='Grupos' ){echo 'active';}else{}?> tab-home-g-b"  href="<?php echo $this->host('ruta')?>/grupo/index/index?tipo=Grupos">
                            GRUPOS
                            <div class="pinchitob"></div>
                        </a>
                    </div>
                </div>
                <div class="contenedor-back-ho"></div>
                </div>
            </div>
        </div>
      
        <!--Login-->
        <div style="display:none">
            <div id="inline_evento" style="padding:10px; background:#fff;">
                <h3>Iniciar sesión</h3>
                <div class="span4 cambiofotouser dev-marca-face">
                <!--<h1>INICIAR CON FACEBOOK</h1>-->
                <?php // if ($this->user): ?>
                  <!--<a href="<?php echo $this->logoutUrl; ?>">Logout</a>-->
                <?php // else: ?>
<!--                  <a href="https://www.facebook.com/dialog/oauth?client_id=171038663080276&redirect_uri=http%3A%2F%2Fdev.juntate.pe%2Fregistrarse&state=e9c59e51d167dd4f29e13536a4930380&scope=email%2Cpublish_stream%2Cread_friendlists">
                    <img src="/img/face.png">
                  </a>-->
                <?php // endif ?>
              </div>
                <?php
                $form = $this->formlogeo;
                $form->setAttributes(array(
                    'action' => $this->url('login/process', array(
                        'action' => 'authenticate'
                    )),
                    'class' => 'bs-docs-example form-horizontal login-home'
                ));
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                 <input type="hidden" name="origen" value="" id="origen" />
                 <input type="hidden" name="accion" value="<?php echo $this->accion;?>" />
        			<div class="control-group">
        				<label class="control-label" for="inputEmail">Correo:</label>
        				<div class="controls">
                            <?php echo $this->formRow($form->get('va_email'));?>
                        </div>
        			</div>
        			<div class="control-group">
        				<label class="control-label" for="inputPassword">Contraseña:</label>
        				<div class="controls">
                            <?php  echo $this->formRow($form->get('va_contrasena'));?>
                        </div>
        			</div>
        			<div class="control-group">
        				<div class="controls">
                            <?php  echo $this->formSubmit($form->get('submit'));?>
                        </div>
        			</div>
        			<div class="control-group" style="margin-bottom:0!important;">
        				<div class="controls">
                            <span class="reg-spam"><a href="/registrarse">Resgistrate</a></span>
                            <span><a href="/cambio">¿Olvidaste tu contraseña?</a></span>
        				</div>
        			</div>
                    <?php  echo $this->form()->closeTag(); ?>

                    <div class="content-login-facebook">
                        <p>Ingresa rápido por:</p>
                        <p><a href="https://www.facebook.com/dialog/oauth?client_id=171038663080276&redirect_uri=http%3A%2F%2Fdev.juntate.pe%2Fregistrarse&state=3d251eca3c8619715dfc14abcea1140d&scope=email%2Cpublish_stream%2Cread_friendlists"></a></p>
                    </div>
            </div>
	</div>
