<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Grupos</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!--<link rel="stylesheet" href="css/normalize.min.css">-->
        <link rel="stylesheet" href="<?php echo $this->host('ruta')?>/css/bootstrap.css">
        <link rel="stylesheet" href="<?php echo $this->host('ruta')?>/css/bootstrap-responsive.css">
        <link rel="stylesheet" href="<?php echo $this->host('ruta')?>/css/main.css">

      <link href="<?php echo $this->host('ruta')?>/css/page.css" rel="stylesheet"/>
      <link href="<?php echo $this->host('ruta')?>/css/theme.css" rel="stylesheet"/>
      <?php echo $this->headLink(); ?>
		
      <script src="<?php echo $this->host('ruta')?>/js/modernizr.js"></script>
      <script src="<?php echo $this->host('ruta')?>/js/vendor/jquery.js"></script>
      <script src="<?php echo $this->host('ruta')?>/js/masonry.js"></script>

    </head>
    <body id="blog">
        <div class="navbar navbar-inverse navbar-fixed-top menu-grup">
            <div class="navbar-inner">
                <div class="container">
                  <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </a>
                  <a class="brand" href="/">Grupos</a>
                  <div class="nav-collapse collapse navbar-responsive-collapse">
                    <ul class="nav pull-right menu-dev">
                        <li class="top-ini"><a href="Login.html">Iniciar sesion</a></li>
                        <li class="divider-vertical divider-one"></li>
                        <li class="top-ini"><a href="/usuario/index/agregarusuario">Registrarse</a></li>
                        
                        <!--<li class="dropdown">
                            <a href="#" class="buttom dropdown-toggle" data-toggle="dropdown">
                                jesser pariona
                                <img src="img/user-avatar.jpg" alt="">
                            </a>
                            <ul class="dropdown-menu">
                              <li><a href="#">Mi perfil</a></li>
                              <li><a href="#">Mis eventos</a></li>
                              <li><a href="#">Mis grupos</a></li>
                              <li class="divider"></li>
                              <li><a href="#">Cerrar sesión</a></li>
                            </ul>
                        </li>-->
                    </ul>
                  </div><!-- /.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="search">
            <div class="container">
                <div class="row-fluid">
                    <div class="span9 form-search">
                        <form METHOD="post" class="form-search span8 dropdown" name="search" action="<?php echo $this->host('ruta')?>/grupo/index/index">
                            <input type="text" name="dato" class="input-medium search-query span10 dropdown-toggle" data-toggle="dropdown">
                            <ul class="dropdown-menu" id="menu-categoria">
                                <li class="man-dev">
                                    <ul>  
                                        <?php 
                                        foreach ($this->categorias  as $categorias) :
                                        ?>
                                        <li><a href="#"><?php echo $this->escapeHtml($categorias->va_nombre); ?></a></li>
                                        <?php endforeach; ?>  
                                    </ul>
                                </li>       
                            </ul>
                            <input type="submit"  class="btn btn-primary btn-evento-i" value="Buscar"/>
                        </form>
                        <a href="#inline_evento" class="btn btn-success btn-home-evnt inlineEvento"><i class="icon-white icon-ok"></i> Crear un evento</a>
                        <!--<a href="crear-evento.html" class="btn btn-success btn-home-evnt"><i class="icon-white icon-ok"></i> Crear un evento</a>-->
                    </div>
                    <div class="span3 btn-evento">
                        <div class="btn-group group-right" data-toggle="buttons-radio"> 
                            <a class="btn btn-primary  active" href="<?php echo $this->host('ruta')?>/grupo/index/index?tipo=Eventos">Eventos</a>
                            <a class="btn btn-primary  active" href="<?php echo $this->host('ruta')?>/grupo/index/index?tipo=Grupos">Grupos</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        
        