<html>
<head>
	<title>Juntate.pe</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

	<style type="text/css">
		body{
			background: #121212 url('/img/wire_bunny.gif') no-repeat 50% 340px;
		}
		#error {
			width: 430px;
			margin: 0 auto;
			background: #ffcc00;
		}
		#error h1 {
			float: left;
			display: inline;
			width: 418px;
			height: 75px;
			margin: 70px 0 70px 0;
			color: white;
			font-family: arial;
			font-size: 50px;
		}
		#error h2 {
			float: left;
			display: inline;
			clear: both;
			margin: 1px 0 6px 4px;
			font-family: arial;
			font-weight: normal;
			font-size: 18px;
			color: #c1eb82;
		}
		#error p {
			float: left;
			display: inline;
			clear: both;
			margin: 1px 0 6px 4px;
			font-size: 13px;
			font-style: normal;
			line-height: 1.26em;
			color: #fff;
			font-family: arial;
		}
		#error a {
			float: left;
			clear: both;
			margin-bottom: 3px;
			color: #00A4DE;
		}
	</style>
</head>
<body>
	<div id="error">
		<h1>Página no encontrada</h1>
    	<p>La página que buscas no existe, probablemente el enlace que usaste es erróneo, intenta ubicarlo en la página principal o usa el buscador para encontrar la noticia que buscas:
    		<br />
    		<br /><a href="/">Volver a la página principal</a>
    	</p>
	</div>
</body>
</html>